In [1]:
import librosa as lr
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import math
import logging

from torch.utils.data import Dataset, DataLoader
from matplotlib import pyplot  


class VoiceSamples(Dataset):
    
    def __init__(self, core_name, samples_path=None, Automatic=None):
        
        self.Log = logging.getLogger()
        logging.basicConfig(level=logging.INFO)
        
        self.noiseThreshold = 1
        
        self.core_name = core_name
        self.samples_path = samples_path
        
        self.soundSamples = []
        self.sampleRate = []
        self.path = []
        
        self.chopedSamples = []
        self.chopedSr = []
        
        self.tensorMelgrams = []
        
        
        self.info = " VoiceSamples Object successfully created "
        self.Log.info(self.info)
        
        
        if Automatic:
            self.LoadSoundSamples()
            self.ChopToOneSecFragments()
            self.ChopedSignalsToTenosor()
        
    def __len__(self):
        return len(self.tensorMelgrams)
    
    def __getitem__(self, idx):
        if self.tensorMelgrams:
            return self.tensorMelgrams[idx]

    def LoadSoundSamples(self):
    
        n = 1

        while(True):
            try:
                if  self.samples_path:
                    path =  self.samples_path + self.core_name + str(n)
                else:
                    path = self.core_name + str(n)

                soundSample, sampleRate = lr.load(path)

                n += 1
                self.soundSamples.append(soundSample)
                self.sampleRate.append(sampleRate) 
                self.path.append(path)

                self.info = " Sample : " + path + " : successfully added"
                self.Log.info(self.info)

            except FileNotFoundError:
                if self.soundSamples:
                    self.info = "That's the end of database : " + str(n-1) + " : Samples added"
                    self.Log.info(self.info)
                    n = 0
                    
                    return self.soundSamples, self.sampleRate, self.path

                else:
                    self.Log.exception("Files are missing")
                    n = 0

                break

            except Exception as ex:      
                self.Log.exception("Unexpected error")
                break
        
    def getSoundSample(self, idx):
        return self.soundSamples[idx], self.sampleRate[idx]
    
    def getSoundSampleLen(self):
        try:
            if len(self.soundSamples) == len(self.sampleRate):
                return len(self.soundSamples)
            else:
                self.Log.warning("Lists: sundSamples and sampleRate are not equal!")
                
        except Exception as e:
            self.Log.exception("Unexpected error" + e)
    
    def ChopToOneSecFragments(self):
        
        # TODO: make shure user goes step by step 
        
        try:
            if len(self.soundSamples) == len(self.sampleRate):
                for idx in range(len(self.soundSamples)):
                    
                    soundSample = self.soundSamples[idx]
                    sr = self.sampleRate[idx]
                    
                    frag_max = math.trunc(len(soundSample)/float(sr))
                    step = math.trunc(sr/2);
                    last_sample = len(soundSample)

                    for frag in range(frag_max*2):
                        start = step * frag
                        stop = start + sr
                        if sr<len(soundSample):
                            if self.checkIfNotNoise(soundSample[start:stop]):
                                self.chopedSamples.append(soundSample[start:stop])
                                self.chopedSr.append(sr)
                                self.info = self.path[idx] + " : " + str(frag+1) + " : successfully choped"
                                self.Log.info(self.info)
                            else:
                                self.info = self.path[idx] + " : " + str(frag+1) + " : NOISE!"
                                self.Log.info(self.info)
                        else:
                            self.Log.warning("Something went wrong")
                            
                    if self.checkIfNotNoise(soundSample[last_sample-sr:last_sample]):
                         # incuding samples cuted by math.trunc() 
                        self.chopedSamples.append(soundSample[last_sample-sr:last_sample])
                        self.chopedSr.append(sr)
                        self.info = self.path[idx] +  " : "  + str(frag_max*2+1) + " : successfully choped"
                        self.Log.info(self.info)
                    else:
                        self.info = self.path[idx] + " : "  + str(frag+1) + " : NOISE!"
                        self.Log.info(self.info)
                
                if self.chopedSamples:
                    self.Log.info("Sucessfully choped all loaded signals and eliminated the noise!")
                    return self.chopedSamples, self.chopedSr 
                    
            else:
                self.Log.warning("Lists: sundSamples and sampleRate are not equal!")
                
        except Exception as e:
            self.e = "Unexpected error : " + str(e)
            self.Log.exception(self.e)
            
    def getChoped(self, idx):
        return self.chopedSamples[idx], self.chopedSr[idx]
        
    def getChopedLen(self):
        try:
            if len(self.chopedSamples) == len(self.chopedSr):
                    return len(self.chopedSamples)
            else:
                self.Log.warning("Lists: sundSamples and sampleRate are not equal!")
                
        except Exception as e:
            self.Log.exception("Unexpected error" + e)
            
        
    def ChopedSignalsToTenosor(self):
        
        # TODO: make shure user goes step by step 
        
        try:
        
            if len(self.chopedSamples) == len(self.chopedSr):
                for idx in range(len(self.chopedSamples)):

                    # hop length adjusted
                    STFT_signal = np.abs(lr.stft(self.chopedSamples[idx], n_fft = 512, hop_length = round(self.chopedSr[idx]/256))) 
                    STFT_signal = lr.power_to_db(STFT_signal**2,ref=np.max)

                    Melgram = STFT_signal[0:256,0:256]
                    TMelgram = torch.tensor(Melgram)
                    self.tensorMelgrams.append(TMelgram)
                    
                    self.info = " " + self.samples_path +  " : ChopedSample " + str(idx) + " : " + " : converted to tensor"
                    self.Log.info(self.info)
                
                if self.tensorMelgrams:
                    self.Log.info("Sucessfully converted all ChopedSamples to Tensors!")
                    return self.tensorMelgrams
                
            else:
                self.Log.warning("Lists: chopedSamples and chopedSr are not equal!")
                
        except Exception as e:
            self.e = "Unexpected error : " + str(e)
            self.Log.exception(self.e)
                
    
    
    def checkIfNotNoise(self, chopedSample):
    
        chopedSamplePow2 = []

        for n in range(len(chopedSample)):
            chopedSamplePow2.append(chopedSample[n]**2)
        sk = sum(chopedSamplePow2)
        if sk > self.noiseThreshold:
            return True 
        else:
            return False

In [2]:
# Use torch.save(tensor, 'file.pt') and torch.load('file.pt')

class VoiceSamplesInput():
    def __init__(self):
        
        self.vsKrystian = VoiceSamples("vsKrystian", samples_path="database/Krystian/" , Automatic=True)
        self.vsNicia = VoiceSamples("vsNicia", samples_path="database/Nicia/" , Automatic=True)

        self.targetKrystian = torch.tensor([[float(1),float(0)]])
        self.targetNicia = torch.tensor([[float(0),float(1)]])
        
        
    def __getitem__(self, idx):
        if idx % 2 == 0:
            return self.vsKrystian[int(idx/2)] ,  self.targetKrystian
        else:
            return self.vsNicia[int((idx+1)/2)] , self.targetNicia
    
    def __len__(self):
        if len(self.vsKrystian) <= len(self.vsNicia):
            return len(self.vsKrystian) * 2
        else:
            return len(self.vsNicia) * 2
            




In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class VoiceRecogModel(nn.Module):

    def __init__(self):
        super(VoiceRecogModel, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 10, 3)
        self.conv2 = nn.Conv2d(10, 20, 3)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(20*62*62, 2000)  # ?? from image dimension
        self.fc2 = nn.Linear(2000, 300)
        self.fc3 = nn.Linear(300, 2)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), 2)
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

In [4]:
import torch.optim as optim

# create dataset : loading and processing samples to tensors
vsInput = VoiceSamplesInput()


INFO:root: VoiceSamples Object successfully created 
/home/krys/.local/lib/python3.7/site-packages/librosa/core/audio.py:146: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
INFO:root: Sample : database/Krystian/vsKrystian1 : successfully added
/home/krys/.local/lib/python3.7/site-packages/librosa/core/audio.py:146: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
INFO:root: Sample : database/Krystian/vsKrystian2 : successfully added
/home/krys/.local/lib/python3.7/site-packages/librosa/core/audio.py:146: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
INFO:root: Sample : database/Krystian/vsKrystian3 : successfully added
/home/krys/.local/lib/python3.7/site-packages/librosa/core/audio.py:146: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.

INFO:root:database/Krystian/vsKrystian2 : 58 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 59 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 60 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 61 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 62 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 63 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 64 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 65 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 66 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 67 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 68 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 69 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 70 : NOISE!
INFO:root:database/Krystian/vsKrystian2 : 71 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 72 : successfully choped
INFO:roo

INFO:root:database/Krystian/vsKrystian4 : 5 : successfully choped
INFO:root:database/Krystian/vsKrystian4 : 6 : successfully choped
INFO:root:database/Krystian/vsKrystian4 : 7 : successfully choped
INFO:root:database/Krystian/vsKrystian4 : 8 : successfully choped
INFO:root:database/Krystian/vsKrystian4 : 9 : successfully choped
INFO:root:database/Krystian/vsKrystian4 : 10 : successfully choped
INFO:root:database/Krystian/vsKrystian4 : 11 : successfully choped
INFO:root:database/Krystian/vsKrystian4 : 12 : successfully choped
INFO:root:database/Krystian/vsKrystian4 : 13 : successfully choped
INFO:root:database/Krystian/vsKrystian4 : 14 : successfully choped
INFO:root:database/Krystian/vsKrystian4 : 15 : successfully choped
INFO:root:database/Krystian/vsKrystian4 : 16 : successfully choped
INFO:root:database/Krystian/vsKrystian4 : 17 : successfully choped
INFO:root:database/Krystian/vsKrystian4 : 18 : successfully choped
INFO:root:database/Krystian/vsKrystian4 : 19 : successfully choped


INFO:root:database/Krystian/vsKrystian6 : 40 : successfully choped
INFO:root:database/Krystian/vsKrystian6 : 41 : successfully choped
INFO:root:database/Krystian/vsKrystian6 : 42 : successfully choped
INFO:root:database/Krystian/vsKrystian6 : 43 : successfully choped
INFO:root:database/Krystian/vsKrystian6 : 44 : successfully choped
INFO:root:database/Krystian/vsKrystian6 : 45 : successfully choped
INFO:root:database/Krystian/vsKrystian6 : 46 : successfully choped
INFO:root:database/Krystian/vsKrystian6 : 47 : successfully choped
INFO:root:database/Krystian/vsKrystian6 : 48 : successfully choped
INFO:root:database/Krystian/vsKrystian6 : 49 : successfully choped
INFO:root:database/Krystian/vsKrystian6 : 50 : successfully choped
INFO:root:database/Krystian/vsKrystian6 : 51 : successfully choped
INFO:root:database/Krystian/vsKrystian6 : 52 : successfully choped
INFO:root:database/Krystian/vsKrystian6 : 53 : successfully choped
INFO:root:database/Krystian/vsKrystian6 : 54 : NOISE!
INFO:roo

INFO:root:database/Krystian/vsKrystian7 : 110 : successfully choped
INFO:root:database/Krystian/vsKrystian7 : 111 : successfully choped
INFO:root:database/Krystian/vsKrystian7 : 112 : successfully choped
INFO:root:database/Krystian/vsKrystian7 : 113 : successfully choped
INFO:root:database/Krystian/vsKrystian7 : 114 : successfully choped
INFO:root:database/Krystian/vsKrystian7 : 115 : NOISE!
INFO:root:database/Krystian/vsKrystian7 : 116 : successfully choped
INFO:root:database/Krystian/vsKrystian7 : 117 : successfully choped
INFO:root:database/Krystian/vsKrystian8 : 1 : successfully choped
INFO:root:database/Krystian/vsKrystian8 : 2 : successfully choped
INFO:root:database/Krystian/vsKrystian8 : 3 : successfully choped
INFO:root:database/Krystian/vsKrystian8 : 4 : successfully choped
INFO:root:database/Krystian/vsKrystian8 : 5 : successfully choped
INFO:root:database/Krystian/vsKrystian8 : 6 : successfully choped
INFO:root:database/Krystian/vsKrystian8 : 7 : successfully choped
INFO:ro

INFO:root:database/Krystian/vsKrystian9 : 42 : successfully choped
INFO:root:database/Krystian/vsKrystian9 : 43 : successfully choped
INFO:root:database/Krystian/vsKrystian9 : 44 : successfully choped
INFO:root:database/Krystian/vsKrystian9 : 45 : successfully choped
INFO:root:database/Krystian/vsKrystian9 : 46 : successfully choped
INFO:root:database/Krystian/vsKrystian9 : 47 : successfully choped
INFO:root:database/Krystian/vsKrystian9 : 48 : successfully choped
INFO:root:database/Krystian/vsKrystian9 : 49 : successfully choped
INFO:root:database/Krystian/vsKrystian9 : 50 : successfully choped
INFO:root:database/Krystian/vsKrystian9 : 51 : successfully choped
INFO:root:database/Krystian/vsKrystian9 : 52 : successfully choped
INFO:root:database/Krystian/vsKrystian9 : 53 : successfully choped
INFO:root:database/Krystian/vsKrystian9 : 54 : successfully choped
INFO:root:database/Krystian/vsKrystian9 : 55 : successfully choped
INFO:root:database/Krystian/vsKrystian9 : 56 : successfully ch

INFO:root:database/Krystian/vsKrystian11 : 42 : successfully choped
INFO:root:database/Krystian/vsKrystian11 : 43 : successfully choped
INFO:root:database/Krystian/vsKrystian11 : 44 : successfully choped
INFO:root:database/Krystian/vsKrystian11 : 45 : successfully choped
INFO:root:database/Krystian/vsKrystian11 : 46 : successfully choped
INFO:root:database/Krystian/vsKrystian11 : 47 : successfully choped
INFO:root:database/Krystian/vsKrystian11 : 48 : successfully choped
INFO:root:database/Krystian/vsKrystian11 : 49 : successfully choped
INFO:root:database/Krystian/vsKrystian11 : 50 : successfully choped
INFO:root:database/Krystian/vsKrystian11 : 51 : successfully choped
INFO:root:database/Krystian/vsKrystian11 : 52 : successfully choped
INFO:root:database/Krystian/vsKrystian11 : 53 : successfully choped
INFO:root:database/Krystian/vsKrystian11 : 54 : successfully choped
INFO:root:database/Krystian/vsKrystian11 : 55 : successfully choped
INFO:root:database/Krystian/vsKrystian11 : 56 : 

INFO:root: database/Krystian/ : ChopedSample 76 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 77 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 78 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 79 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 80 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 81 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 82 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 83 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 84 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 85 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 86 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 87 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 88 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 89 :  

INFO:root: database/Krystian/ : ChopedSample 188 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 189 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 190 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 191 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 192 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 193 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 194 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 195 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 196 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 197 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 198 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 199 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 200 :  : converted to tensor
INFO:root: database/Krystian/ : Choped

INFO:root: database/Krystian/ : ChopedSample 299 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 300 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 301 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 302 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 303 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 304 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 305 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 306 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 307 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 308 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 309 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 310 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 311 :  : converted to tensor
INFO:root: database/Krystian/ : Choped

INFO:root: database/Krystian/ : ChopedSample 410 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 411 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 412 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 413 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 414 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 415 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 416 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 417 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 418 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 419 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 420 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 421 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 422 :  : converted to tensor
INFO:root: database/Krystian/ : Choped

INFO:root: database/Krystian/ : ChopedSample 521 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 522 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 523 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 524 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 525 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 526 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 527 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 528 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 529 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 530 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 531 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 532 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 533 :  : converted to tensor
INFO:root: database/Krystian/ : Choped

INFO:root: database/Krystian/ : ChopedSample 632 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 633 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 634 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 635 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 636 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 637 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 638 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 639 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 640 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 641 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 642 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 643 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 644 :  : converted to tensor
INFO:root: database/Krystian/ : Choped

INFO:root:database/Nicia/vsNicia1 : 27 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 28 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 29 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 30 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 31 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 32 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 33 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 34 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 35 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 36 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 37 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 38 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 39 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 40 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 41 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 42 : successfully choped
INFO:root:database/Nicia

INFO:root:database/Nicia/vsNicia2 : 84 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 85 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 86 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 87 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 88 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 89 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 90 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 91 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 92 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 93 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 94 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 95 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 96 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 97 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 98 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 99 : successfully choped
INFO:root:database/Nicia

INFO:root:database/Nicia/vsNicia3 : 24 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 25 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 26 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 27 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 28 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 29 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 30 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 31 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 32 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 33 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 34 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 35 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 36 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 37 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 38 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 39 : successfully choped
INFO:root:database/Nicia

INFO:root:database/Nicia/vsNicia3 : 158 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 159 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 160 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 161 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 162 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 163 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 164 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 165 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 166 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 167 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 168 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 169 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 170 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 171 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 172 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 173 : successfully choped
INFO:roo

INFO:root:database/Nicia/vsNicia3 : 291 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 292 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 293 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 294 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 295 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 296 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 297 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 298 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 299 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 300 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 301 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 302 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 303 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 304 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 305 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 306 : successfully choped
INFO:roo

INFO:root:database/Nicia/vsNicia3 : 424 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 425 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 426 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 427 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 428 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 429 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 430 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 431 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 432 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 433 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 434 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 435 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 436 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 437 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 438 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 439 : successfully choped
INFO:roo

INFO:root:database/Nicia/vsNicia3 : 557 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 558 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 559 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 560 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 561 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 562 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 563 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 564 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 565 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 566 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 567 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 568 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 569 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 570 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 571 : successfully choped
INFO:root:database/Nicia/vsNicia3 : 572 : successfully choped
INFO:roo

INFO:root: database/Nicia/ : ChopedSample 18 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 19 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 20 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 21 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 22 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 23 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 24 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 25 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 26 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 27 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 28 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 29 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 30 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 31 :  : converted to tensor
INFO:root: database/

INFO:root: database/Nicia/ : ChopedSample 135 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 136 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 137 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 138 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 139 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 140 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 141 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 142 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 143 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 144 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 145 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 146 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 147 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 148 :  : converted to tensor
INFO:r

INFO:root: database/Nicia/ : ChopedSample 251 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 252 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 253 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 254 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 255 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 256 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 257 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 258 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 259 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 260 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 261 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 262 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 263 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 264 :  : converted to tensor
INFO:r

INFO:root: database/Nicia/ : ChopedSample 367 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 368 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 369 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 370 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 371 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 372 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 373 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 374 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 375 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 376 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 377 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 378 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 379 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 380 :  : converted to tensor
INFO:r

INFO:root: database/Nicia/ : ChopedSample 483 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 484 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 485 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 486 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 487 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 488 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 489 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 490 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 491 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 492 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 493 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 494 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 495 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 496 :  : converted to tensor
INFO:r

INFO:root: database/Nicia/ : ChopedSample 599 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 600 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 601 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 602 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 603 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 604 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 605 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 606 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 607 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 608 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 609 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 610 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 611 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 612 :  : converted to tensor
INFO:r

INFO:root: database/Nicia/ : ChopedSample 715 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 716 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 717 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 718 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 719 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 720 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 721 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 722 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 723 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 724 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 725 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 726 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 727 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 728 :  : converted to tensor
INFO:r

INFO:root: database/Nicia/ : ChopedSample 831 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 832 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 833 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 834 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 835 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 836 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 837 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 838 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 839 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 840 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 841 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 842 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 843 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 844 :  : converted to tensor
INFO:r

In [12]:
# create net from VoiceRecogModel
net = VoiceRecogModel()

# loss function (using function implemented in pytorch)
criterion = nn.MSELoss()

# create your optimizer (basic optimizer)
# setting learning rate 
optimizer = optim.SGD(net.parameters(), lr=0.001)

In [13]:
import logging
logging.basicConfig(level=logging.INFO)
trainLog = logging.getLogger()

# Training Loop

# How many times learn on the same dataset
epoch = 1
for i in range(epoch):   
    for k in range(len(vsInput)):  
        try:
            vs, target = vsInput[k]

            optimizer.zero_grad()   # zero the gradient buffers
            input = vs.view(-1,1,256,256)
            output = net(input)

            loss = criterion(output, target)

            loss.backward()
            optimizer.step()    # Does the update


            info = "Training " + str(k)+"/"+str(len(vsInput))+" done"

            print("\n")
            print(target)
            print(output)
            print(loss)
            print(info)
        except Exception as e:
            print(e)
            pass



tensor([[1., 0.]])
tensor([[ 0.2650, -0.2483]], grad_fn=<AddmmBackward>)
tensor(0.3009, grad_fn=<MseLossBackward>)
Training 0/1412 done


tensor([[0., 1.]])
tensor([[6.2864, 0.9393]], grad_fn=<AddmmBackward>)
tensor(19.7612, grad_fn=<MseLossBackward>)
Training 1/1412 done


tensor([[1., 0.]])
tensor([[-0.3570, -0.0792]], grad_fn=<AddmmBackward>)
tensor(0.9239, grad_fn=<MseLossBackward>)
Training 2/1412 done


tensor([[0., 1.]])
tensor([[ 1.2121, -0.1732]], grad_fn=<AddmmBackward>)
tensor(1.4228, grad_fn=<MseLossBackward>)
Training 3/1412 done


tensor([[1., 0.]])
tensor([[-0.0202,  0.3052]], grad_fn=<AddmmBackward>)
tensor(0.5670, grad_fn=<MseLossBackward>)
Training 4/1412 done


tensor([[0., 1.]])
tensor([[0.0281, 0.1592]], grad_fn=<AddmmBackward>)
tensor(0.3539, grad_fn=<MseLossBackward>)
Training 5/1412 done


tensor([[1., 0.]])
tensor([[0.0428, 0.4387]], grad_fn=<AddmmBackward>)
tensor(0.5543, grad_fn=<MseLossBackward>)
Training 6/1412 done


tensor([[0., 1.]])
tensor([[0.0869, 0



tensor([[1., 0.]])
tensor([[0.2364, 0.3308]], grad_fn=<AddmmBackward>)
tensor(0.3462, grad_fn=<MseLossBackward>)
Training 60/1412 done


tensor([[0., 1.]])
tensor([[0.6088, 0.7342]], grad_fn=<AddmmBackward>)
tensor(0.2206, grad_fn=<MseLossBackward>)
Training 61/1412 done


tensor([[1., 0.]])
tensor([[0.2725, 0.4044]], grad_fn=<AddmmBackward>)
tensor(0.3464, grad_fn=<MseLossBackward>)
Training 62/1412 done


tensor([[0., 1.]])
tensor([[0.3535, 0.5039]], grad_fn=<AddmmBackward>)
tensor(0.1855, grad_fn=<MseLossBackward>)
Training 63/1412 done


tensor([[1., 0.]])
tensor([[0.5597, 0.8120]], grad_fn=<AddmmBackward>)
tensor(0.4266, grad_fn=<MseLossBackward>)
Training 64/1412 done


tensor([[0., 1.]])
tensor([[0.1363, 0.2209]], grad_fn=<AddmmBackward>)
tensor(0.3128, grad_fn=<MseLossBackward>)
Training 65/1412 done


tensor([[1., 0.]])
tensor([[0.5473, 0.5930]], grad_fn=<AddmmBackward>)
tensor(0.2783, grad_fn=<MseLossBackward>)
Training 66/1412 done


tensor([[0., 1.]])
tensor([[0.4682, 0.4



tensor([[1., 0.]])
tensor([[0.3988, 0.5026]], grad_fn=<AddmmBackward>)
tensor(0.3071, grad_fn=<MseLossBackward>)
Training 120/1412 done


tensor([[0., 1.]])
tensor([[0.4855, 0.5781]], grad_fn=<AddmmBackward>)
tensor(0.2069, grad_fn=<MseLossBackward>)
Training 121/1412 done


tensor([[1., 0.]])
tensor([[0.3637, 0.4783]], grad_fn=<AddmmBackward>)
tensor(0.3168, grad_fn=<MseLossBackward>)
Training 122/1412 done


tensor([[0., 1.]])
tensor([[0.4883, 0.5474]], grad_fn=<AddmmBackward>)
tensor(0.2217, grad_fn=<MseLossBackward>)
Training 123/1412 done


tensor([[1., 0.]])
tensor([[0.4031, 0.4988]], grad_fn=<AddmmBackward>)
tensor(0.3026, grad_fn=<MseLossBackward>)
Training 124/1412 done


tensor([[0., 1.]])
tensor([[0.4883, 0.5418]], grad_fn=<AddmmBackward>)
tensor(0.2242, grad_fn=<MseLossBackward>)
Training 125/1412 done


tensor([[1., 0.]])
tensor([[0.4122, 0.4989]], grad_fn=<AddmmBackward>)
tensor(0.2972, grad_fn=<MseLossBackward>)
Training 126/1412 done


tensor([[0., 1.]])
tensor([[0.49



tensor([[1., 0.]])
tensor([[0.4345, 0.4817]], grad_fn=<AddmmBackward>)
tensor(0.2759, grad_fn=<MseLossBackward>)
Training 180/1412 done


tensor([[0., 1.]])
tensor([[0.5540, 0.5227]], grad_fn=<AddmmBackward>)
tensor(0.2674, grad_fn=<MseLossBackward>)
Training 181/1412 done


tensor([[1., 0.]])
tensor([[0.3923, 0.4528]], grad_fn=<AddmmBackward>)
tensor(0.2872, grad_fn=<MseLossBackward>)
Training 182/1412 done


tensor([[0., 1.]])
tensor([[0.4879, 0.4765]], grad_fn=<AddmmBackward>)
tensor(0.2560, grad_fn=<MseLossBackward>)
Training 183/1412 done


tensor([[1., 0.]])
tensor([[0.4193, 0.4957]], grad_fn=<AddmmBackward>)
tensor(0.2915, grad_fn=<MseLossBackward>)
Training 184/1412 done


tensor([[0., 1.]])
tensor([[0.5256, 0.5372]], grad_fn=<AddmmBackward>)
tensor(0.2452, grad_fn=<MseLossBackward>)
Training 185/1412 done


tensor([[1., 0.]])
tensor([[0.3949, 0.4715]], grad_fn=<AddmmBackward>)
tensor(0.2942, grad_fn=<MseLossBackward>)
Training 186/1412 done


tensor([[0., 1.]])
tensor([[0.53



tensor([[1., 0.]])
tensor([[0.3999, 0.5103]], grad_fn=<AddmmBackward>)
tensor(0.3102, grad_fn=<MseLossBackward>)
Training 240/1412 done


tensor([[0., 1.]])
tensor([[0.5068, 0.5710]], grad_fn=<AddmmBackward>)
tensor(0.2204, grad_fn=<MseLossBackward>)
Training 241/1412 done


tensor([[1., 0.]])
tensor([[0.3566, 0.4616]], grad_fn=<AddmmBackward>)
tensor(0.3136, grad_fn=<MseLossBackward>)
Training 242/1412 done


tensor([[0., 1.]])
tensor([[0.4977, 0.5656]], grad_fn=<AddmmBackward>)
tensor(0.2182, grad_fn=<MseLossBackward>)
Training 243/1412 done


tensor([[1., 0.]])
tensor([[0.3486, 0.4542]], grad_fn=<AddmmBackward>)
tensor(0.3153, grad_fn=<MseLossBackward>)
Training 244/1412 done


tensor([[0., 1.]])
tensor([[0.5077, 0.6376]], grad_fn=<AddmmBackward>)
tensor(0.1945, grad_fn=<MseLossBackward>)
Training 245/1412 done


tensor([[1., 0.]])
tensor([[0.3801, 0.4451]], grad_fn=<AddmmBackward>)
tensor(0.2912, grad_fn=<MseLossBackward>)
Training 246/1412 done


tensor([[0., 1.]])
tensor([[0.44



tensor([[1., 0.]])
tensor([[0.2727, 0.3254]], grad_fn=<AddmmBackward>)
tensor(0.3174, grad_fn=<MseLossBackward>)
Training 300/1412 done


tensor([[0., 1.]])
tensor([[0.5519, 0.7700]], grad_fn=<AddmmBackward>)
tensor(0.1788, grad_fn=<MseLossBackward>)
Training 301/1412 done


tensor([[1., 0.]])
tensor([[0.3022, 0.3798]], grad_fn=<AddmmBackward>)
tensor(0.3156, grad_fn=<MseLossBackward>)
Training 302/1412 done


tensor([[0., 1.]])
tensor([[0.4160, 0.6055]], grad_fn=<AddmmBackward>)
tensor(0.1643, grad_fn=<MseLossBackward>)
Training 303/1412 done


tensor([[1., 0.]])
tensor([[0.4498, 0.5422]], grad_fn=<AddmmBackward>)
tensor(0.2984, grad_fn=<MseLossBackward>)
Training 304/1412 done


tensor([[0., 1.]])
tensor([[0.4203, 0.5966]], grad_fn=<AddmmBackward>)
tensor(0.1697, grad_fn=<MseLossBackward>)
Training 305/1412 done


tensor([[1., 0.]])
tensor([[0.4747, 0.4652]], grad_fn=<AddmmBackward>)
tensor(0.2462, grad_fn=<MseLossBackward>)
Training 306/1412 done


tensor([[0., 1.]])
tensor([[0.43



tensor([[1., 0.]])
tensor([[0.5653, 0.5817]], grad_fn=<AddmmBackward>)
tensor(0.2636, grad_fn=<MseLossBackward>)
Training 360/1412 done


tensor([[0., 1.]])
tensor([[0.4439, 0.6119]], grad_fn=<AddmmBackward>)
tensor(0.1738, grad_fn=<MseLossBackward>)
Training 361/1412 done


tensor([[1., 0.]])
tensor([[0.3142, 0.3497]], grad_fn=<AddmmBackward>)
tensor(0.2963, grad_fn=<MseLossBackward>)
Training 362/1412 done


tensor([[0., 1.]])
tensor([[0.6792, 0.5675]], grad_fn=<AddmmBackward>)
tensor(0.3242, grad_fn=<MseLossBackward>)
Training 363/1412 done


tensor([[1., 0.]])
tensor([[0.2927, 0.3488]], grad_fn=<AddmmBackward>)
tensor(0.3110, grad_fn=<MseLossBackward>)
Training 364/1412 done


tensor([[0., 1.]])
tensor([[0.4511, 0.4914]], grad_fn=<AddmmBackward>)
tensor(0.2311, grad_fn=<MseLossBackward>)
Training 365/1412 done


tensor([[1., 0.]])
tensor([[0.4404, 0.5900]], grad_fn=<AddmmBackward>)
tensor(0.3306, grad_fn=<MseLossBackward>)
Training 366/1412 done


tensor([[0., 1.]])
tensor([[0.36



tensor([[1., 0.]])
tensor([[0.4817, 0.5783]], grad_fn=<AddmmBackward>)
tensor(0.3015, grad_fn=<MseLossBackward>)
Training 420/1412 done


tensor([[0., 1.]])
tensor([[0.3324, 0.7105]], grad_fn=<AddmmBackward>)
tensor(0.0971, grad_fn=<MseLossBackward>)
Training 421/1412 done


tensor([[1., 0.]])
tensor([[0.3281, 0.4394]], grad_fn=<AddmmBackward>)
tensor(0.3223, grad_fn=<MseLossBackward>)
Training 422/1412 done


tensor([[0., 1.]])
tensor([[0.6454, 0.7112]], grad_fn=<AddmmBackward>)
tensor(0.2499, grad_fn=<MseLossBackward>)
Training 423/1412 done


tensor([[1., 0.]])
tensor([[0.2339, 0.2920]], grad_fn=<AddmmBackward>)
tensor(0.3361, grad_fn=<MseLossBackward>)
Training 424/1412 done


tensor([[0., 1.]])
tensor([[0.4485, 0.8970]], grad_fn=<AddmmBackward>)
tensor(0.1059, grad_fn=<MseLossBackward>)
Training 425/1412 done


tensor([[1., 0.]])
tensor([[0.3768, 0.4479]], grad_fn=<AddmmBackward>)
tensor(0.2945, grad_fn=<MseLossBackward>)
Training 426/1412 done


tensor([[0., 1.]])
tensor([[0.36



tensor([[1., 0.]])
tensor([[0.3443, 0.3272]], grad_fn=<AddmmBackward>)
tensor(0.2685, grad_fn=<MseLossBackward>)
Training 480/1412 done


tensor([[0., 1.]])
tensor([[0.4447, 0.5912]], grad_fn=<AddmmBackward>)
tensor(0.1825, grad_fn=<MseLossBackward>)
Training 481/1412 done


tensor([[1., 0.]])
tensor([[0.5090, 0.4336]], grad_fn=<AddmmBackward>)
tensor(0.2146, grad_fn=<MseLossBackward>)
Training 482/1412 done


tensor([[0., 1.]])
tensor([[0.3308, 0.6047]], grad_fn=<AddmmBackward>)
tensor(0.1328, grad_fn=<MseLossBackward>)
Training 483/1412 done


tensor([[1., 0.]])
tensor([[0.5465, 0.4011]], grad_fn=<AddmmBackward>)
tensor(0.1833, grad_fn=<MseLossBackward>)
Training 484/1412 done


tensor([[0., 1.]])
tensor([[0.4036, 0.7744]], grad_fn=<AddmmBackward>)
tensor(0.1069, grad_fn=<MseLossBackward>)
Training 485/1412 done


tensor([[1., 0.]])
tensor([[0.4997, 0.3767]], grad_fn=<AddmmBackward>)
tensor(0.1961, grad_fn=<MseLossBackward>)
Training 486/1412 done


tensor([[0., 1.]])
tensor([[0.40



tensor([[0., 1.]])
tensor([[0.6009, 0.6964]], grad_fn=<AddmmBackward>)
tensor(0.2266, grad_fn=<MseLossBackward>)
Training 541/1412 done


tensor([[1., 0.]])
tensor([[0.2243, 0.3749]], grad_fn=<AddmmBackward>)
tensor(0.3711, grad_fn=<MseLossBackward>)
Training 542/1412 done


tensor([[0., 1.]])
tensor([[0.3571, 0.8938]], grad_fn=<AddmmBackward>)
tensor(0.0694, grad_fn=<MseLossBackward>)
Training 543/1412 done


tensor([[1., 0.]])
tensor([[0.4284, 0.3579]], grad_fn=<AddmmBackward>)
tensor(0.2274, grad_fn=<MseLossBackward>)
Training 544/1412 done


tensor([[0., 1.]])
tensor([[0.3198, 0.9736]], grad_fn=<AddmmBackward>)
tensor(0.0515, grad_fn=<MseLossBackward>)
Training 545/1412 done


tensor([[1., 0.]])
tensor([[0.5260, 0.2953]], grad_fn=<AddmmBackward>)
tensor(0.1559, grad_fn=<MseLossBackward>)
Training 546/1412 done


tensor([[0., 1.]])
tensor([[0.3153, 0.7786]], grad_fn=<AddmmBackward>)
tensor(0.0742, grad_fn=<MseLossBackward>)
Training 547/1412 done


tensor([[1., 0.]])
tensor([[0.60



tensor([[0., 1.]])
tensor([[0.3043, 0.8205]], grad_fn=<AddmmBackward>)
tensor(0.0624, grad_fn=<MseLossBackward>)
Training 601/1412 done


tensor([[1., 0.]])
tensor([[0.4627, 0.3614]], grad_fn=<AddmmBackward>)
tensor(0.2097, grad_fn=<MseLossBackward>)
Training 602/1412 done


tensor([[0., 1.]])
tensor([[0.2928, 0.7119]], grad_fn=<AddmmBackward>)
tensor(0.0844, grad_fn=<MseLossBackward>)
Training 603/1412 done


tensor([[1., 0.]])
tensor([[0.5284, 0.3387]], grad_fn=<AddmmBackward>)
tensor(0.1685, grad_fn=<MseLossBackward>)
Training 604/1412 done


tensor([[0., 1.]])
tensor([[0.4914, 0.5222]], grad_fn=<AddmmBackward>)
tensor(0.2349, grad_fn=<MseLossBackward>)
Training 605/1412 done


tensor([[1., 0.]])
tensor([[0.6490, 0.3263]], grad_fn=<AddmmBackward>)
tensor(0.1148, grad_fn=<MseLossBackward>)
Training 606/1412 done


tensor([[0., 1.]])
tensor([[0.4317, 0.5332]], grad_fn=<AddmmBackward>)
tensor(0.2021, grad_fn=<MseLossBackward>)
Training 607/1412 done


tensor([[1., 0.]])
tensor([[0.72



tensor([[0., 1.]])
tensor([[-0.0222,  1.1335]], grad_fn=<AddmmBackward>)
tensor(0.0092, grad_fn=<MseLossBackward>)
Training 661/1412 done


tensor([[1., 0.]])
tensor([[ 0.8881, -0.0216]], grad_fn=<AddmmBackward>)
tensor(0.0065, grad_fn=<MseLossBackward>)
Training 662/1412 done


tensor([[0., 1.]])
tensor([[-0.0492,  1.1430]], grad_fn=<AddmmBackward>)
tensor(0.0114, grad_fn=<MseLossBackward>)
Training 663/1412 done


tensor([[1., 0.]])
tensor([[0.7394, 0.1169]], grad_fn=<AddmmBackward>)
tensor(0.0408, grad_fn=<MseLossBackward>)
Training 664/1412 done


tensor([[0., 1.]])
tensor([[0.3216, 0.7313]], grad_fn=<AddmmBackward>)
tensor(0.0878, grad_fn=<MseLossBackward>)
Training 665/1412 done


tensor([[1., 0.]])
tensor([[0.8295, 0.1708]], grad_fn=<AddmmBackward>)
tensor(0.0291, grad_fn=<MseLossBackward>)
Training 666/1412 done


tensor([[0., 1.]])
tensor([[0.5097, 0.3551]], grad_fn=<AddmmBackward>)
tensor(0.3378, grad_fn=<MseLossBackward>)
Training 667/1412 done


tensor([[1., 0.]])
tensor(



tensor([[0., 1.]])
tensor([[0.2622, 0.8377]], grad_fn=<AddmmBackward>)
tensor(0.0475, grad_fn=<MseLossBackward>)
Training 721/1412 done


tensor([[1., 0.]])
tensor([[0.6957, 0.1966]], grad_fn=<AddmmBackward>)
tensor(0.0656, grad_fn=<MseLossBackward>)
Training 722/1412 done


tensor([[0., 1.]])
tensor([[0.1915, 0.8057]], grad_fn=<AddmmBackward>)
tensor(0.0372, grad_fn=<MseLossBackward>)
Training 723/1412 done


tensor([[1., 0.]])
tensor([[0.7512, 0.3854]], grad_fn=<AddmmBackward>)
tensor(0.1052, grad_fn=<MseLossBackward>)
Training 724/1412 done


tensor([[0., 1.]])
tensor([[0.1737, 0.8397]], grad_fn=<AddmmBackward>)
tensor(0.0279, grad_fn=<MseLossBackward>)
Training 725/1412 done


tensor([[1., 0.]])
tensor([[0.9189, 0.1613]], grad_fn=<AddmmBackward>)
tensor(0.0163, grad_fn=<MseLossBackward>)
Training 726/1412 done


tensor([[0., 1.]])
tensor([[-0.2659,  1.3229]], grad_fn=<AddmmBackward>)
tensor(0.0875, grad_fn=<MseLossBackward>)
Training 727/1412 done


tensor([[1., 0.]])
tensor([[ 0



tensor([[1., 0.]])
tensor([[ 1.0791, -0.0022]], grad_fn=<AddmmBackward>)
tensor(0.0031, grad_fn=<MseLossBackward>)
Training 780/1412 done


tensor([[0., 1.]])
tensor([[-0.0935,  1.0498]], grad_fn=<AddmmBackward>)
tensor(0.0056, grad_fn=<MseLossBackward>)
Training 781/1412 done


tensor([[1., 0.]])
tensor([[ 0.9335, -0.0087]], grad_fn=<AddmmBackward>)
tensor(0.0023, grad_fn=<MseLossBackward>)
Training 782/1412 done


tensor([[0., 1.]])
tensor([[0.1490, 0.7578]], grad_fn=<AddmmBackward>)
tensor(0.0404, grad_fn=<MseLossBackward>)
Training 783/1412 done


tensor([[1., 0.]])
tensor([[0.9438, 0.1832]], grad_fn=<AddmmBackward>)
tensor(0.0184, grad_fn=<MseLossBackward>)
Training 784/1412 done


tensor([[0., 1.]])
tensor([[0.1480, 0.8057]], grad_fn=<AddmmBackward>)
tensor(0.0298, grad_fn=<MseLossBackward>)
Training 785/1412 done


tensor([[1., 0.]])
tensor([[0.8417, 0.2507]], grad_fn=<AddmmBackward>)
tensor(0.0440, grad_fn=<MseLossBackward>)
Training 786/1412 done


tensor([[0., 1.]])
tensor(



tensor([[1., 0.]])
tensor([[0.2641, 0.5348]], grad_fn=<AddmmBackward>)
tensor(0.4138, grad_fn=<MseLossBackward>)
Training 840/1412 done


tensor([[0., 1.]])
tensor([[0.0318, 0.4087]], grad_fn=<AddmmBackward>)
tensor(0.1753, grad_fn=<MseLossBackward>)
Training 841/1412 done


tensor([[1., 0.]])
tensor([[0.3741, 0.1769]], grad_fn=<AddmmBackward>)
tensor(0.2115, grad_fn=<MseLossBackward>)
Training 842/1412 done


tensor([[0., 1.]])
tensor([[-0.1054,  1.3075]], grad_fn=<AddmmBackward>)
tensor(0.0528, grad_fn=<MseLossBackward>)
Training 843/1412 done


tensor([[1., 0.]])
tensor([[0.8154, 0.0307]], grad_fn=<AddmmBackward>)
tensor(0.0175, grad_fn=<MseLossBackward>)
Training 844/1412 done


tensor([[0., 1.]])
tensor([[0.0677, 0.9421]], grad_fn=<AddmmBackward>)
tensor(0.0040, grad_fn=<MseLossBackward>)
Training 845/1412 done


tensor([[1., 0.]])
tensor([[ 1.3016, -0.0518]], grad_fn=<AddmmBackward>)
tensor(0.0468, grad_fn=<MseLossBackward>)
Training 846/1412 done


tensor([[0., 1.]])
tensor([[



tensor([[1., 0.]])
tensor([[0.8888, 0.0398]], grad_fn=<AddmmBackward>)
tensor(0.0070, grad_fn=<MseLossBackward>)
Training 900/1412 done


tensor([[0., 1.]])
tensor([[-0.0074,  0.9542]], grad_fn=<AddmmBackward>)
tensor(0.0011, grad_fn=<MseLossBackward>)
Training 901/1412 done


tensor([[1., 0.]])
tensor([[1.1495, 0.0089]], grad_fn=<AddmmBackward>)
tensor(0.0112, grad_fn=<MseLossBackward>)
Training 902/1412 done


tensor([[0., 1.]])
tensor([[-0.0288,  0.7669]], grad_fn=<AddmmBackward>)
tensor(0.0276, grad_fn=<MseLossBackward>)
Training 903/1412 done


tensor([[1., 0.]])
tensor([[0.7391, 0.3331]], grad_fn=<AddmmBackward>)
tensor(0.0895, grad_fn=<MseLossBackward>)
Training 904/1412 done


tensor([[0., 1.]])
tensor([[0.2920, 0.7630]], grad_fn=<AddmmBackward>)
tensor(0.0707, grad_fn=<MseLossBackward>)
Training 905/1412 done


tensor([[1., 0.]])
tensor([[0.7947, 0.1987]], grad_fn=<AddmmBackward>)
tensor(0.0408, grad_fn=<MseLossBackward>)
Training 906/1412 done


tensor([[0., 1.]])
tensor([[



tensor([[1., 0.]])
tensor([[0.8340, 0.0893]], grad_fn=<AddmmBackward>)
tensor(0.0178, grad_fn=<MseLossBackward>)
Training 960/1412 done


tensor([[0., 1.]])
tensor([[-0.1360,  1.0533]], grad_fn=<AddmmBackward>)
tensor(0.0107, grad_fn=<MseLossBackward>)
Training 961/1412 done


tensor([[1., 0.]])
tensor([[0.9477, 0.0772]], grad_fn=<AddmmBackward>)
tensor(0.0043, grad_fn=<MseLossBackward>)
Training 962/1412 done


tensor([[0., 1.]])
tensor([[0.0996, 0.7545]], grad_fn=<AddmmBackward>)
tensor(0.0351, grad_fn=<MseLossBackward>)
Training 963/1412 done


tensor([[1., 0.]])
tensor([[1.1097, 0.1084]], grad_fn=<AddmmBackward>)
tensor(0.0119, grad_fn=<MseLossBackward>)
Training 964/1412 done


tensor([[0., 1.]])
tensor([[-0.1857,  1.2325]], grad_fn=<AddmmBackward>)
tensor(0.0443, grad_fn=<MseLossBackward>)
Training 965/1412 done


tensor([[1., 0.]])
tensor([[ 0.8124, -0.0101]], grad_fn=<AddmmBackward>)
tensor(0.0177, grad_fn=<MseLossBackward>)
Training 966/1412 done


tensor([[0., 1.]])
tensor(



tensor([[1., 0.]])
tensor([[0.9961, 0.0024]], grad_fn=<AddmmBackward>)
tensor(1.0585e-05, grad_fn=<MseLossBackward>)
Training 1020/1412 done


tensor([[0., 1.]])
tensor([[0.2512, 0.4713]], grad_fn=<AddmmBackward>)
tensor(0.1713, grad_fn=<MseLossBackward>)
Training 1021/1412 done


tensor([[1., 0.]])
tensor([[0.9796, 0.1642]], grad_fn=<AddmmBackward>)
tensor(0.0137, grad_fn=<MseLossBackward>)
Training 1022/1412 done


tensor([[0., 1.]])
tensor([[0.1387, 0.5858]], grad_fn=<AddmmBackward>)
tensor(0.0954, grad_fn=<MseLossBackward>)
Training 1023/1412 done


tensor([[1., 0.]])
tensor([[0.8972, 0.5736]], grad_fn=<AddmmBackward>)
tensor(0.1698, grad_fn=<MseLossBackward>)
Training 1024/1412 done


tensor([[0., 1.]])
tensor([[0.3880, 0.5108]], grad_fn=<AddmmBackward>)
tensor(0.1950, grad_fn=<MseLossBackward>)
Training 1025/1412 done


tensor([[1., 0.]])
tensor([[0.6604, 0.2053]], grad_fn=<AddmmBackward>)
tensor(0.0787, grad_fn=<MseLossBackward>)
Training 1026/1412 done


tensor([[0., 1.]])
te



tensor([[0., 1.]])
tensor([[0.2985, 0.5415]], grad_fn=<AddmmBackward>)
tensor(0.1497, grad_fn=<MseLossBackward>)
Training 1079/1412 done


tensor([[1., 0.]])
tensor([[0.1509, 1.1636]], grad_fn=<AddmmBackward>)
tensor(1.0374, grad_fn=<MseLossBackward>)
Training 1080/1412 done


tensor([[0., 1.]])
tensor([[0.0504, 0.1645]], grad_fn=<AddmmBackward>)
tensor(0.3503, grad_fn=<MseLossBackward>)
Training 1081/1412 done


tensor([[1., 0.]])
tensor([[0.1824, 0.0411]], grad_fn=<AddmmBackward>)
tensor(0.3351, grad_fn=<MseLossBackward>)
Training 1082/1412 done


tensor([[0., 1.]])
tensor([[0.0471, 0.3764]], grad_fn=<AddmmBackward>)
tensor(0.1955, grad_fn=<MseLossBackward>)
Training 1083/1412 done


tensor([[1., 0.]])
tensor([[ 0.5751, -0.0292]], grad_fn=<AddmmBackward>)
tensor(0.0907, grad_fn=<MseLossBackward>)
Training 1084/1412 done


tensor([[0., 1.]])
tensor([[0.0627, 0.4708]], grad_fn=<AddmmBackward>)
tensor(0.1420, grad_fn=<MseLossBackward>)
Training 1085/1412 done


tensor([[1., 0.]])
tens



tensor([[0., 1.]])
tensor([[-0.0613,  1.0605]], grad_fn=<AddmmBackward>)
tensor(0.0037, grad_fn=<MseLossBackward>)
Training 1139/1412 done


tensor([[1., 0.]])
tensor([[ 0.9391, -0.0234]], grad_fn=<AddmmBackward>)
tensor(0.0021, grad_fn=<MseLossBackward>)
Training 1140/1412 done


tensor([[0., 1.]])
tensor([[0.1482, 0.6649]], grad_fn=<AddmmBackward>)
tensor(0.0671, grad_fn=<MseLossBackward>)
Training 1141/1412 done


tensor([[1., 0.]])
tensor([[0.9930, 0.1065]], grad_fn=<AddmmBackward>)
tensor(0.0057, grad_fn=<MseLossBackward>)
Training 1142/1412 done


tensor([[0., 1.]])
tensor([[0.1652, 0.7913]], grad_fn=<AddmmBackward>)
tensor(0.0354, grad_fn=<MseLossBackward>)
Training 1143/1412 done


tensor([[1., 0.]])
tensor([[1.0539, 0.1416]], grad_fn=<AddmmBackward>)
tensor(0.0115, grad_fn=<MseLossBackward>)
Training 1144/1412 done


tensor([[0., 1.]])
tensor([[-0.1168,  1.3647]], grad_fn=<AddmmBackward>)
tensor(0.0733, grad_fn=<MseLossBackward>)
Training 1145/1412 done


tensor([[1., 0.]])




tensor([[1., 0.]])
tensor([[0.9399, 0.2097]], grad_fn=<AddmmBackward>)
tensor(0.0238, grad_fn=<MseLossBackward>)
Training 1198/1412 done


tensor([[0., 1.]])
tensor([[-0.0278,  1.3118]], grad_fn=<AddmmBackward>)
tensor(0.0490, grad_fn=<MseLossBackward>)
Training 1199/1412 done


tensor([[1., 0.]])
tensor([[0.7601, 0.1051]], grad_fn=<AddmmBackward>)
tensor(0.0343, grad_fn=<MseLossBackward>)
Training 1200/1412 done


tensor([[0., 1.]])
tensor([[0.0938, 0.8461]], grad_fn=<AddmmBackward>)
tensor(0.0162, grad_fn=<MseLossBackward>)
Training 1201/1412 done


tensor([[1., 0.]])
tensor([[0.8870, 0.1139]], grad_fn=<AddmmBackward>)
tensor(0.0129, grad_fn=<MseLossBackward>)
Training 1202/1412 done


tensor([[0., 1.]])
tensor([[0.2898, 0.8765]], grad_fn=<AddmmBackward>)
tensor(0.0496, grad_fn=<MseLossBackward>)
Training 1203/1412 done


tensor([[1., 0.]])
tensor([[0.6935, 0.1124]], grad_fn=<AddmmBackward>)
tensor(0.0533, grad_fn=<MseLossBackward>)
Training 1204/1412 done


tensor([[0., 1.]])
tens



tensor([[0., 1.]])
tensor([[-0.1007,  1.4138]], grad_fn=<AddmmBackward>)
tensor(0.0907, grad_fn=<MseLossBackward>)
Training 1257/1412 done


tensor([[1., 0.]])
tensor([[ 0.9824, -0.0607]], grad_fn=<AddmmBackward>)
tensor(0.0020, grad_fn=<MseLossBackward>)
Training 1258/1412 done


tensor([[0., 1.]])
tensor([[0.0288, 0.9441]], grad_fn=<AddmmBackward>)
tensor(0.0020, grad_fn=<MseLossBackward>)
Training 1259/1412 done


tensor([[1., 0.]])
tensor([[ 1.1721, -0.1389]], grad_fn=<AddmmBackward>)
tensor(0.0245, grad_fn=<MseLossBackward>)
Training 1260/1412 done


tensor([[0., 1.]])
tensor([[-0.0779,  0.9485]], grad_fn=<AddmmBackward>)
tensor(0.0044, grad_fn=<MseLossBackward>)
Training 1261/1412 done


tensor([[1., 0.]])
tensor([[ 0.8458, -0.0317]], grad_fn=<AddmmBackward>)
tensor(0.0124, grad_fn=<MseLossBackward>)
Training 1262/1412 done


tensor([[0., 1.]])
tensor([[-0.0074,  0.9936]], grad_fn=<AddmmBackward>)
tensor(4.8132e-05, grad_fn=<MseLossBackward>)
Training 1263/1412 done


tensor([[



tensor([[1., 0.]])
tensor([[ 1.2979, -0.0537]], grad_fn=<AddmmBackward>)
tensor(0.0458, grad_fn=<MseLossBackward>)
Training 1316/1412 done


tensor([[0., 1.]])
tensor([[-0.0776,  0.9272]], grad_fn=<AddmmBackward>)
tensor(0.0057, grad_fn=<MseLossBackward>)
Training 1317/1412 done


tensor([[1., 0.]])
tensor([[0.9178, 0.0062]], grad_fn=<AddmmBackward>)
tensor(0.0034, grad_fn=<MseLossBackward>)
Training 1318/1412 done


tensor([[0., 1.]])
tensor([[0.0272, 0.8768]], grad_fn=<AddmmBackward>)
tensor(0.0080, grad_fn=<MseLossBackward>)
Training 1319/1412 done


tensor([[1., 0.]])
tensor([[1.0088, 0.0126]], grad_fn=<AddmmBackward>)
tensor(0.0001, grad_fn=<MseLossBackward>)
Training 1320/1412 done


tensor([[0., 1.]])
tensor([[0.0190, 1.1832]], grad_fn=<AddmmBackward>)
tensor(0.0170, grad_fn=<MseLossBackward>)
Training 1321/1412 done


tensor([[1., 0.]])
tensor([[ 1.0473, -0.0880]], grad_fn=<AddmmBackward>)
tensor(0.0050, grad_fn=<MseLossBackward>)
Training 1322/1412 done


tensor([[0., 1.]])




tensor([[0., 1.]])
tensor([[0.2660, 0.4580]], grad_fn=<AddmmBackward>)
tensor(0.1823, grad_fn=<MseLossBackward>)
Training 1375/1412 done


tensor([[1., 0.]])
tensor([[1.0592, 0.0506]], grad_fn=<AddmmBackward>)
tensor(0.0030, grad_fn=<MseLossBackward>)
Training 1376/1412 done


tensor([[0., 1.]])
tensor([[0.2526, 0.6374]], grad_fn=<AddmmBackward>)
tensor(0.0976, grad_fn=<MseLossBackward>)
Training 1377/1412 done


tensor([[1., 0.]])
tensor([[1.0310, 0.2020]], grad_fn=<AddmmBackward>)
tensor(0.0209, grad_fn=<MseLossBackward>)
Training 1378/1412 done


tensor([[0., 1.]])
tensor([[0.0473, 0.8629]], grad_fn=<AddmmBackward>)
tensor(0.0105, grad_fn=<MseLossBackward>)
Training 1379/1412 done


tensor([[1., 0.]])
tensor([[0.9677, 0.1416]], grad_fn=<AddmmBackward>)
tensor(0.0106, grad_fn=<MseLossBackward>)
Training 1380/1412 done


tensor([[0., 1.]])
tensor([[0.0992, 0.7259]], grad_fn=<AddmmBackward>)
tensor(0.0425, grad_fn=<MseLossBackward>)
Training 1381/1412 done


tensor([[1., 0.]])
tensor



tensor([[0., 1.]])
tensor([[0.2670, 0.6840]], grad_fn=<AddmmBackward>)
tensor(0.0856, grad_fn=<MseLossBackward>)
Training 23/1412 done


tensor([[1., 0.]])
tensor([[0.8993, 0.0028]], grad_fn=<AddmmBackward>)
tensor(0.0051, grad_fn=<MseLossBackward>)
Training 24/1412 done


tensor([[0., 1.]])
tensor([[0.2922, 0.8056]], grad_fn=<AddmmBackward>)
tensor(0.0616, grad_fn=<MseLossBackward>)
Training 25/1412 done


tensor([[1., 0.]])
tensor([[0.6873, 0.1901]], grad_fn=<AddmmBackward>)
tensor(0.0670, grad_fn=<MseLossBackward>)
Training 26/1412 done


tensor([[0., 1.]])
tensor([[0.2729, 0.7225]], grad_fn=<AddmmBackward>)
tensor(0.0757, grad_fn=<MseLossBackward>)
Training 27/1412 done


tensor([[1., 0.]])
tensor([[0.6365, 0.1466]], grad_fn=<AddmmBackward>)
tensor(0.0768, grad_fn=<MseLossBackward>)
Training 28/1412 done


tensor([[0., 1.]])
tensor([[0.7129, 0.4326]], grad_fn=<AddmmBackward>)
tensor(0.4150, grad_fn=<MseLossBackward>)
Training 29/1412 done


tensor([[1., 0.]])
tensor([[0.5464, 0.4



tensor([[0., 1.]])
tensor([[-0.2241,  1.3070]], grad_fn=<AddmmBackward>)
tensor(0.0722, grad_fn=<MseLossBackward>)
Training 83/1412 done


KeyboardInterrupt: 

In [14]:
PATH = "/home/krys/POLIBUDA/nn_VoiceRecognition_Models/modelV5.pt"
torch.save(net.state_dict(), PATH)