In [1]:
import librosa as lr
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import math
import logging

from torch.utils.data import Dataset, DataLoader
from matplotlib import pyplot  


class VoiceSamples(Dataset):
    
    def __init__(self, core_name, samples_path=None, Automatic=None):
        
        self.Log = logging.getLogger()
        logging.basicConfig(level=logging.INFO)
        
        self.noiseThreshold = 1
        
        self.core_name = core_name
        self.samples_path = samples_path
        
        self.soundSamples = []
        self.sampleRate = []
        self.path = []
        
        self.chopedSamples = []
        self.chopedSr = []
        
        self.tensorMelgrams = []
        
        
        self.info = " VoiceSamples Object successfully created "
        self.Log.info(self.info)
        
        
        if Automatic:
            self.LoadSoundSamples()
            self.ChopToOneSecFragments()
            self.ChopedSignalsToTenosor()
        
    def __len__(self):
        return len(self.tensorMelgrams)
    
    def __getitem__(self, idx):
        if self.tensorMelgrams:
            return self.tensorMelgrams[idx]

    def LoadSoundSamples(self):
    
        n = 1

        while(True):
            try:
                if  self.samples_path:
                    path =  self.samples_path + self.core_name + str(n)
                else:
                    path = self.core_name + str(n)

                soundSample, sampleRate = lr.load(path)

                n += 1
                self.soundSamples.append(soundSample)
                self.sampleRate.append(sampleRate) 
                self.path.append(path)

                self.info = " Sample : " + path + " : successfully added"
                self.Log.info(self.info)

            except FileNotFoundError:
                if self.soundSamples:
                    self.info = "That's the end of database : " + str(n-1) + " : Samples added"
                    self.Log.info(self.info)
                    n = 0
                    
                    return self.soundSamples, self.sampleRate, self.path

                else:
                    self.Log.exception("Files are missing")
                    n = 0

                break

            except Exception as ex:      
                self.Log.exception("Unexpected error")
                break
        
    def getSoundSample(self, idx):
        return self.soundSamples[idx], self.sampleRate[idx]
    
    def getSoundSampleLen(self):
        try:
            if len(self.soundSamples) == len(self.sampleRate):
                return len(self.soundSamples)
            else:
                self.Log.warning("Lists: sundSamples and sampleRate are not equal!")
                
        except Exception as e:
            self.Log.exception("Unexpected error" + e)
    
    def ChopToOneSecFragments(self):
        
        # TODO: make shure user goes step by step 
        
        try:
            if len(self.soundSamples) == len(self.sampleRate):
                for idx in range(len(self.soundSamples)):
                    
                    soundSample = self.soundSamples[idx]
                    sr = self.sampleRate[idx]
                    
                    frag_max = math.trunc(len(soundSample)/float(sr))
                    step = math.trunc(sr/2);
                    last_sample = len(soundSample)

                    for frag in range(frag_max*2):
                        start = step * frag
                        stop = start + sr
                        if sr<len(soundSample):
                            if self.checkIfNotNoise(soundSample[start:stop]):
                                self.chopedSamples.append(soundSample[start:stop])
                                self.chopedSr.append(sr)
                                self.info = self.path[idx] + " : " + str(frag+1) + " : successfully choped"
                                self.Log.info(self.info)
                            else:
                                self.info = self.path[idx] + " : " + str(frag+1) + " : NOISE!"
                                self.Log.info(self.info)
                        else:
                            self.Log.warning("Something went wrong")
                            
                    if self.checkIfNotNoise(soundSample[last_sample-sr:last_sample]):
                         # incuding samples cuted by math.trunc() 
                        self.chopedSamples.append(soundSample[last_sample-sr:last_sample])
                        self.chopedSr.append(sr)
                        self.info = self.path[idx] +  " : "  + str(frag_max*2+1) + " : successfully choped"
                        self.Log.info(self.info)
                    else:
                        self.info = self.path[idx] + " : "  + str(frag+1) + " : NOISE!"
                        self.Log.info(self.info)
                
                if self.chopedSamples:
                    self.Log.info("Sucessfully choped all loaded signals and eliminated the noise!")
                    return self.chopedSamples, self.chopedSr 
                    
            else:
                self.Log.warning("Lists: sundSamples and sampleRate are not equal!")
                
        except Exception as e:
            self.e = "Unexpected error : " + str(e)
            self.Log.exception(self.e)
            
    def getChoped(self, idx):
        return self.chopedSamples[idx], self.chopedSr[idx]
        
    def getChopedLen(self):
        try:
            if len(self.chopedSamples) == len(self.chopedSr):
                    return len(self.chopedSamples)
            else:
                self.Log.warning("Lists: sundSamples and sampleRate are not equal!")
                
        except Exception as e:
            self.Log.exception("Unexpected error" + e)
            
        
    def ChopedSignalsToTenosor(self):
        
        # TODO: make shure user goes step by step 
        
        try:
        
            if len(self.chopedSamples) == len(self.chopedSr):
                for idx in range(len(self.chopedSamples)):

                    # hop length adjusted
                    STFT_signal = np.abs(lr.stft(self.chopedSamples[idx], n_fft = 512, hop_length = round(self.chopedSr[idx]/256))) 
                    STFT_signal = lr.power_to_db(STFT_signal**2,ref=np.max)

                    Melgram = STFT_signal[0:256,0:256]
                    TMelgram = torch.tensor(Melgram)
                    self.tensorMelgrams.append(TMelgram)
                    
                    self.info = " " + self.samples_path +  " : ChopedSample " + str(idx) + " : " + " : converted to tensor"
                    self.Log.info(self.info)
                
                if self.tensorMelgrams:
                    self.Log.info("Sucessfully converted all ChopedSamples to Tensors!")
                    return self.tensorMelgrams
                
            else:
                self.Log.warning("Lists: chopedSamples and chopedSr are not equal!")
                
        except Exception as e:
            self.e = "Unexpected error : " + str(e)
            self.Log.exception(self.e)
                
    
    
    def checkIfNotNoise(self, chopedSample):
    
        chopedSamplePow2 = []

        for n in range(len(chopedSample)):
            chopedSamplePow2.append(chopedSample[n]**2)
        sk = sum(chopedSamplePow2)
        if sk > self.noiseThreshold:
            return True 
        else:
            return False

In [2]:
# Use torch.save(tensor, 'file.pt') and torch.load('file.pt')

class VoiceSamplesInput():
    def __init__(self):
        
        self.vsKrystian = VoiceSamples("vsKrystian", samples_path="database/Krystian/" , Automatic=True)
        self.vsNicia = VoiceSamples("vsNicia", samples_path="database/Nicia/" , Automatic=True)

        self.targetKrystian = torch.tensor([[float(1),float(0)]])
        self.targetNicia = torch.tensor([[float(0),float(1)]])
        
        
    def __getitem__(self, idx):
        if idx % 2 == 0:
            return self.vsKrystian[int(idx/2)] ,  self.targetKrystian
        else:
            return self.vsNicia[int((idx+1)/2)] , self.targetNicia
    
    def __len__(self):
        if len(self.vsKrystian) <= len(self.vsNicia):
            return len(self.vsKrystian) * 2
        else:
            return len(self.vsNicia) * 2
            




In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class VoiceRecogModel(nn.Module):

    def __init__(self):
        super(VoiceRecogModel, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16*62*62, 120)  # ?? from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 2)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), 2)
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

In [4]:
import torch.optim as optim

# create dataset : loading and processing samples to tensors
vsInput = VoiceSamplesInput()


INFO:root: VoiceSamples Object successfully created 
/home/krys/.local/lib/python3.7/site-packages/librosa/core/audio.py:146: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
INFO:root: Sample : database/Krystian/vsKrystian1 : successfully added
/home/krys/.local/lib/python3.7/site-packages/librosa/core/audio.py:146: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
INFO:root: Sample : database/Krystian/vsKrystian2 : successfully added
/home/krys/.local/lib/python3.7/site-packages/librosa/core/audio.py:146: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
INFO:root:That's the end of database : 2 : Samples added
INFO:root:database/Krystian/vsKrystian1 : 1 : successfully choped
INFO:root:database/Krystian/vsKrystian1 : 2 : successfully choped
INFO:root:database/Krysti

INFO:root:database/Krystian/vsKrystian2 : 94 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 95 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 96 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 97 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 98 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 99 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 100 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 101 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 102 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 103 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 104 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 105 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 106 : successfully choped
INFO:root:database/Krystian/vsKrystian2 : 107 : NOISE!
INFO:root:database/Krystian/vsKrystian2 : 108 : successfully choped

INFO:root: database/Krystian/ : ChopedSample 73 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 74 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 75 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 76 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 77 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 78 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 79 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 80 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 81 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 82 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 83 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 84 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 85 :  : converted to tensor
INFO:root: database/Krystian/ : ChopedSample 86 :  

INFO:root:database/Nicia/vsNicia1 : 37 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 38 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 39 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 40 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 41 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 42 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 43 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 44 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 45 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 46 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 47 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 48 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 49 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 50 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 51 : successfully choped
INFO:root:database/Nicia/vsNicia1 : 52 : successfully choped
INFO:root:database/Nicia

INFO:root:database/Nicia/vsNicia2 : 94 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 95 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 96 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 97 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 98 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 99 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 100 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 101 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 102 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 103 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 104 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 105 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 106 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 107 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 108 : successfully choped
INFO:root:database/Nicia/vsNicia2 : 109 : successfully choped
INFO:root:data

INFO:root: database/Nicia/ : ChopedSample 27 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 28 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 29 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 30 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 31 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 32 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 33 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 34 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 35 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 36 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 37 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 38 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 39 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 40 :  : converted to tensor
INFO:root: database/

INFO:root: database/Nicia/ : ChopedSample 144 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 145 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 146 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 147 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 148 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 149 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 150 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 151 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 152 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 153 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 154 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 155 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 156 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 157 :  : converted to tensor
INFO:r

INFO:root: database/Nicia/ : ChopedSample 260 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 261 :  : converted to tensor
INFO:root: database/Nicia/ : ChopedSample 262 :  : converted to tensor
INFO:root:Sucessfully converted all ChopedSamples to Tensors!


In [9]:
# create net from VoiceRecogModel
net = VoiceRecogModel()

# loss function (using function implemented in pytorch)
criterion = nn.MSELoss()

# create your optimizer (basic optimizer)
# setting learning rate 
optimizer = optim.SGD(net.parameters(), lr=0.01)

In [10]:
import logging
logging.basicConfig(level=logging.INFO)
trainLog = logging.getLogger()

# Training Loop

for k in range(len(vsInput)):  
    
    vs, target = vsInput[k]
    
    vs_n = (vs+80)/80
    
    optimizer.zero_grad()   # zero the gradient buffers
    input = vs_n.view(-1,1,256,256)
    output = net(input)
    print(target)
    print(output)
    loss = criterion(output, target)
    print(loss)
    loss.backward()
    optimizer.step()    # Does the update
    info = "Training " + str(k)+"/"+str(len(vsInput))+" done"
    trainLog.info(info)

INFO:root:Training 0/286 done
INFO:root:Training 1/286 done
INFO:root:Training 2/286 done
INFO:root:Training 3/286 done
INFO:root:Training 4/286 done


tensor([[1., 0.]])
tensor([[ 0.1377, -0.0440]], grad_fn=<AddmmBackward>)
tensor(0.3728, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[ 0.2048, -0.0287]], grad_fn=<AddmmBackward>)
tensor(0.5500, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.1923, 0.0625]], grad_fn=<AddmmBackward>)
tensor(0.3282, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.2555, 0.0746]], grad_fn=<AddmmBackward>)
tensor(0.4609, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.2585, 0.1755]], grad_fn=<AddmmBackward>)
tensor(0.2903, grad_fn=<MseLossBackward>)


INFO:root:Training 5/286 done
INFO:root:Training 6/286 done
INFO:root:Training 7/286 done
INFO:root:Training 8/286 done


tensor([[0., 1.]])
tensor([[0.3211, 0.1603]], grad_fn=<AddmmBackward>)
tensor(0.4041, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.3146, 0.2921]], grad_fn=<AddmmBackward>)
tensor(0.2775, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.3738, 0.2599]], grad_fn=<AddmmBackward>)
tensor(0.3437, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.3617, 0.3858]], grad_fn=<AddmmBackward>)
tensor(0.2781, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.4276, 0.3329]], grad_fn=<AddmmBackward>)
tensor(0.3140, grad_fn=<MseLossBackward>)


INFO:root:Training 9/286 done
INFO:root:Training 10/286 done
INFO:root:Training 11/286 done
INFO:root:Training 12/286 done
INFO:root:Training 13/286 done


tensor([[1., 0.]])
tensor([[0.3943, 0.4481]], grad_fn=<AddmmBackward>)
tensor(0.2839, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.4596, 0.3781]], grad_fn=<AddmmBackward>)
tensor(0.2990, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4264, 0.4924]], grad_fn=<AddmmBackward>)
tensor(0.2857, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.4806, 0.4000]], grad_fn=<AddmmBackward>)
tensor(0.2955, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4404, 0.5093]], grad_fn=<AddmmBackward>)
tensor(0.2863, grad_fn=<MseLossBackward>)


INFO:root:Training 14/286 done
INFO:root:Training 15/286 done
INFO:root:Training 16/286 done
INFO:root:Training 17/286 done
INFO:root:Training 18/286 done


tensor([[0., 1.]])
tensor([[0.4930, 0.4133]], grad_fn=<AddmmBackward>)
tensor(0.2936, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4500, 0.5136]], grad_fn=<AddmmBackward>)
tensor(0.2831, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.4953, 0.4198]], grad_fn=<AddmmBackward>)
tensor(0.2910, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4669, 0.5361]], grad_fn=<AddmmBackward>)
tensor(0.2858, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.4926, 0.4090]], grad_fn=<AddmmBackward>)
tensor(0.2960, grad_fn=<MseLossBackward>)


INFO:root:Training 19/286 done
INFO:root:Training 20/286 done
INFO:root:Training 21/286 done
INFO:root:Training 22/286 done
INFO:root:Training 23/286 done


tensor([[1., 0.]])
tensor([[0.4668, 0.5191]], grad_fn=<AddmmBackward>)
tensor(0.2769, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.4970, 0.4097]], grad_fn=<AddmmBackward>)
tensor(0.2977, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4708, 0.5193]], grad_fn=<AddmmBackward>)
tensor(0.2749, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5067, 0.4187]], grad_fn=<AddmmBackward>)
tensor(0.2973, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4735, 0.5175]], grad_fn=<AddmmBackward>)
tensor(0.2725, grad_fn=<MseLossBackward>)


INFO:root:Training 24/286 done
INFO:root:Training 25/286 done
INFO:root:Training 26/286 done
INFO:root:Training 27/286 done
INFO:root:Training 28/286 done


tensor([[0., 1.]])
tensor([[0.5156, 0.4301]], grad_fn=<AddmmBackward>)
tensor(0.2953, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4734, 0.5169]], grad_fn=<AddmmBackward>)
tensor(0.2723, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5095, 0.4260]], grad_fn=<AddmmBackward>)
tensor(0.2946, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4462, 0.4707]], grad_fn=<AddmmBackward>)
tensor(0.2641, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5122, 0.4440]], grad_fn=<AddmmBackward>)
tensor(0.2857, grad_fn=<MseLossBackward>)


INFO:root:Training 29/286 done
INFO:root:Training 30/286 done
INFO:root:Training 31/286 done
INFO:root:Training 32/286 done
INFO:root:Training 33/286 done


tensor([[1., 0.]])
tensor([[0.4823, 0.5415]], grad_fn=<AddmmBackward>)
tensor(0.2806, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5005, 0.4215]], grad_fn=<AddmmBackward>)
tensor(0.2926, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4791, 0.5231]], grad_fn=<AddmmBackward>)
tensor(0.2725, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5045, 0.4226]], grad_fn=<AddmmBackward>)
tensor(0.2940, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4807, 0.5208]], grad_fn=<AddmmBackward>)
tensor(0.2705, grad_fn=<MseLossBackward>)


INFO:root:Training 34/286 done
INFO:root:Training 35/286 done
INFO:root:Training 36/286 done
INFO:root:Training 37/286 done
INFO:root:Training 38/286 done


tensor([[0., 1.]])
tensor([[0.5010, 0.4193]], grad_fn=<AddmmBackward>)
tensor(0.2941, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4857, 0.5192]], grad_fn=<AddmmBackward>)
tensor(0.2671, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.4927, 0.4056]], grad_fn=<AddmmBackward>)
tensor(0.2980, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4918, 0.5191]], grad_fn=<AddmmBackward>)
tensor(0.2639, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.4981, 0.4061]], grad_fn=<AddmmBackward>)
tensor(0.3004, grad_fn=<MseLossBackward>)


INFO:root:Training 39/286 done
INFO:root:Training 40/286 done
INFO:root:Training 41/286 done
INFO:root:Training 42/286 done
INFO:root:Training 43/286 done


tensor([[1., 0.]])
tensor([[0.4928, 0.5138]], grad_fn=<AddmmBackward>)
tensor(0.2606, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5016, 0.4122]], grad_fn=<AddmmBackward>)
tensor(0.2986, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4906, 0.5068]], grad_fn=<AddmmBackward>)
tensor(0.2582, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5109, 0.4221]], grad_fn=<AddmmBackward>)
tensor(0.2975, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4876, 0.5040]], grad_fn=<AddmmBackward>)
tensor(0.2583, grad_fn=<MseLossBackward>)


INFO:root:Training 44/286 done
INFO:root:Training 45/286 done
INFO:root:Training 46/286 done
INFO:root:Training 47/286 done
INFO:root:Training 48/286 done


tensor([[0., 1.]])
tensor([[0.5124, 0.4255]], grad_fn=<AddmmBackward>)
tensor(0.2963, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4876, 0.5052]], grad_fn=<AddmmBackward>)
tensor(0.2589, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5107, 0.4289]], grad_fn=<AddmmBackward>)
tensor(0.2935, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4883, 0.5053]], grad_fn=<AddmmBackward>)
tensor(0.2586, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5051, 0.4257]], grad_fn=<AddmmBackward>)
tensor(0.2925, grad_fn=<MseLossBackward>)


INFO:root:Training 49/286 done
INFO:root:Training 50/286 done
INFO:root:Training 51/286 done
INFO:root:Training 52/286 done
INFO:root:Training 53/286 done


tensor([[1., 0.]])
tensor([[0.4897, 0.5071]], grad_fn=<AddmmBackward>)
tensor(0.2588, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5056, 0.4269]], grad_fn=<AddmmBackward>)
tensor(0.2920, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4909, 0.5097]], grad_fn=<AddmmBackward>)
tensor(0.2595, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5076, 0.4299]], grad_fn=<AddmmBackward>)
tensor(0.2913, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4930, 0.5085]], grad_fn=<AddmmBackward>)
tensor(0.2578, grad_fn=<MseLossBackward>)


INFO:root:Training 54/286 done
INFO:root:Training 55/286 done
INFO:root:Training 56/286 done
INFO:root:Training 57/286 done
INFO:root:Training 58/286 done


tensor([[0., 1.]])
tensor([[0.5076, 0.4307]], grad_fn=<AddmmBackward>)
tensor(0.2908, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4780, 0.4991]], grad_fn=<AddmmBackward>)
tensor(0.2608, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5109, 0.4379]], grad_fn=<AddmmBackward>)
tensor(0.2885, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4739, 0.4916]], grad_fn=<AddmmBackward>)
tensor(0.2593, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5092, 0.4429]], grad_fn=<AddmmBackward>)
tensor(0.2848, grad_fn=<MseLossBackward>)


INFO:root:Training 59/286 done
INFO:root:Training 60/286 done
INFO:root:Training 61/286 done
INFO:root:Training 62/286 done
INFO:root:Training 63/286 done


tensor([[1., 0.]])
tensor([[0.4885, 0.5094]], grad_fn=<AddmmBackward>)
tensor(0.2606, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5045, 0.4366]], grad_fn=<AddmmBackward>)
tensor(0.2860, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4928, 0.5148]], grad_fn=<AddmmBackward>)
tensor(0.2611, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.4974, 0.4286]], grad_fn=<AddmmBackward>)
tensor(0.2870, grad_fn=<MseLossBackward>)


INFO:root:Training 64/286 done
INFO:root:Training 65/286 done
INFO:root:Training 66/286 done
INFO:root:Training 67/286 done


tensor([[1., 0.]])
tensor([[0.4916, 0.5093]], grad_fn=<AddmmBackward>)
tensor(0.2590, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5080, 0.4400]], grad_fn=<AddmmBackward>)
tensor(0.2858, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4939, 0.5113]], grad_fn=<AddmmBackward>)
tensor(0.2588, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5084, 0.4399]], grad_fn=<AddmmBackward>)
tensor(0.2861, grad_fn=<MseLossBackward>)


INFO:root:Training 68/286 done
INFO:root:Training 69/286 done
INFO:root:Training 70/286 done
INFO:root:Training 71/286 done


tensor([[1., 0.]])
tensor([[0.4860, 0.5022]], grad_fn=<AddmmBackward>)
tensor(0.2582, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5067, 0.4411]], grad_fn=<AddmmBackward>)
tensor(0.2845, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4926, 0.5088]], grad_fn=<AddmmBackward>)
tensor(0.2582, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5082, 0.4409]], grad_fn=<AddmmBackward>)
tensor(0.2854, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4852, 0.5074]], grad_fn=<AddmmBackward>)
tensor(0.2613, grad_fn=<MseLossBackward>)


INFO:root:Training 72/286 done
INFO:root:Training 73/286 done
INFO:root:Training 74/286 done
INFO:root:Training 75/286 done
INFO:root:Training 76/286 done


tensor([[0., 1.]])
tensor([[0.5084, 0.4418]], grad_fn=<AddmmBackward>)
tensor(0.2850, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4905, 0.5068]], grad_fn=<AddmmBackward>)
tensor(0.2582, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5064, 0.4413]], grad_fn=<AddmmBackward>)
tensor(0.2843, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4906, 0.5126]], grad_fn=<AddmmBackward>)
tensor(0.2611, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5045, 0.4406]], grad_fn=<AddmmBackward>)
tensor(0.2837, grad_fn=<MseLossBackward>)


INFO:root:Training 77/286 done
INFO:root:Training 78/286 done
INFO:root:Training 79/286 done
INFO:root:Training 80/286 done
INFO:root:Training 81/286 done


tensor([[1., 0.]])
tensor([[0.4837, 0.5045]], grad_fn=<AddmmBackward>)
tensor(0.2605, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5065, 0.4436]], grad_fn=<AddmmBackward>)
tensor(0.2830, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4893, 0.5094]], grad_fn=<AddmmBackward>)
tensor(0.2602, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5015, 0.4384]], grad_fn=<AddmmBackward>)
tensor(0.2835, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4884, 0.5091]], grad_fn=<AddmmBackward>)
tensor(0.2605, grad_fn=<MseLossBackward>)


INFO:root:Training 82/286 done
INFO:root:Training 83/286 done
INFO:root:Training 84/286 done
INFO:root:Training 85/286 done
INFO:root:Training 86/286 done


tensor([[0., 1.]])
tensor([[0.5072, 0.4441]], grad_fn=<AddmmBackward>)
tensor(0.2831, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4903, 0.5079]], grad_fn=<AddmmBackward>)
tensor(0.2589, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5069, 0.4443]], grad_fn=<AddmmBackward>)
tensor(0.2828, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4864, 0.5031]], grad_fn=<AddmmBackward>)
tensor(0.2585, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5047, 0.4419]], grad_fn=<AddmmBackward>)
tensor(0.2831, grad_fn=<MseLossBackward>)


INFO:root:Training 87/286 done
INFO:root:Training 88/286 done
INFO:root:Training 89/286 done
INFO:root:Training 90/286 done
INFO:root:Training 91/286 done


tensor([[1., 0.]])
tensor([[0.4888, 0.5078]], grad_fn=<AddmmBackward>)
tensor(0.2596, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5102, 0.4475]], grad_fn=<AddmmBackward>)
tensor(0.2828, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4911, 0.5115]], grad_fn=<AddmmBackward>)
tensor(0.2603, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5059, 0.4441]], grad_fn=<AddmmBackward>)
tensor(0.2825, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4896, 0.5073]], grad_fn=<AddmmBackward>)
tensor(0.2589, grad_fn=<MseLossBackward>)


INFO:root:Training 92/286 done
INFO:root:Training 93/286 done
INFO:root:Training 94/286 done
INFO:root:Training 95/286 done
INFO:root:Training 96/286 done


tensor([[0., 1.]])
tensor([[0.5046, 0.4425]], grad_fn=<AddmmBackward>)
tensor(0.2827, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4913, 0.5078]], grad_fn=<AddmmBackward>)
tensor(0.2583, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5047, 0.4415]], grad_fn=<AddmmBackward>)
tensor(0.2833, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4900, 0.5088]], grad_fn=<AddmmBackward>)
tensor(0.2595, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5035, 0.4448]], grad_fn=<AddmmBackward>)
tensor(0.2809, grad_fn=<MseLossBackward>)


INFO:root:Training 97/286 done
INFO:root:Training 98/286 done
INFO:root:Training 99/286 done
INFO:root:Training 100/286 done
INFO:root:Training 101/286 done


tensor([[1., 0.]])
tensor([[0.4908, 0.5091]], grad_fn=<AddmmBackward>)
tensor(0.2593, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5029, 0.4468]], grad_fn=<AddmmBackward>)
tensor(0.2795, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4892, 0.5068]], grad_fn=<AddmmBackward>)
tensor(0.2589, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.4984, 0.4416]], grad_fn=<AddmmBackward>)
tensor(0.2801, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4922, 0.5085]], grad_fn=<AddmmBackward>)
tensor(0.2582, grad_fn=<MseLossBackward>)


INFO:root:Training 102/286 done
INFO:root:Training 103/286 done
INFO:root:Training 104/286 done
INFO:root:Training 105/286 done
INFO:root:Training 106/286 done


tensor([[0., 1.]])
tensor([[0.5013, 0.4439]], grad_fn=<AddmmBackward>)
tensor(0.2802, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4923, 0.5086]], grad_fn=<AddmmBackward>)
tensor(0.2582, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5027, 0.4459]], grad_fn=<AddmmBackward>)
tensor(0.2799, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4945, 0.5086]], grad_fn=<AddmmBackward>)
tensor(0.2571, grad_fn=<MseLossBackward>)


INFO:root:Training 107/286 done
INFO:root:Training 108/286 done
INFO:root:Training 109/286 done
INFO:root:Training 110/286 done


tensor([[0., 1.]])
tensor([[0.5071, 0.4486]], grad_fn=<AddmmBackward>)
tensor(0.2806, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4954, 0.5052]], grad_fn=<AddmmBackward>)
tensor(0.2549, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5055, 0.4466]], grad_fn=<AddmmBackward>)
tensor(0.2809, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4908, 0.5033]], grad_fn=<AddmmBackward>)
tensor(0.2563, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5083, 0.4480]], grad_fn=<AddmmBackward>)
tensor(0.2815, grad_fn=<MseLossBackward>)


INFO:root:Training 111/286 done
INFO:root:Training 112/286 done
INFO:root:Training 113/286 done
INFO:root:Training 114/286 done
INFO:root:Training 115/286 done


tensor([[1., 0.]])
tensor([[0.4941, 0.5067]], grad_fn=<AddmmBackward>)
tensor(0.2563, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5046, 0.4465]], grad_fn=<AddmmBackward>)
tensor(0.2805, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4879, 0.5025]], grad_fn=<AddmmBackward>)
tensor(0.2574, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5037, 0.4488]], grad_fn=<AddmmBackward>)
tensor(0.2788, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4908, 0.5055]], grad_fn=<AddmmBackward>)
tensor(0.2574, grad_fn=<MseLossBackward>)


INFO:root:Training 116/286 done
INFO:root:Training 117/286 done
INFO:root:Training 118/286 done
INFO:root:Training 119/286 done
INFO:root:Training 120/286 done


tensor([[0., 1.]])
tensor([[0.5047, 0.4486]], grad_fn=<AddmmBackward>)
tensor(0.2794, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4929, 0.5067]], grad_fn=<AddmmBackward>)
tensor(0.2570, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5105, 0.4524]], grad_fn=<AddmmBackward>)
tensor(0.2803, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4926, 0.5061]], grad_fn=<AddmmBackward>)
tensor(0.2568, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5095, 0.4546]], grad_fn=<AddmmBackward>)
tensor(0.2785, grad_fn=<MseLossBackward>)


INFO:root:Training 121/286 done
INFO:root:Training 122/286 done
INFO:root:Training 123/286 done
INFO:root:Training 124/286 done
INFO:root:Training 125/286 done
INFO:root:Training 126/286 done


tensor([[1., 0.]])
tensor([[0.4932, 0.5073]], grad_fn=<AddmmBackward>)
tensor(0.2571, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5006, 0.4456]], grad_fn=<AddmmBackward>)
tensor(0.2790, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4950, 0.5097]], grad_fn=<AddmmBackward>)
tensor(0.2574, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5036, 0.4476]], grad_fn=<AddmmBackward>)
tensor(0.2793, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4911, 0.5051]], grad_fn=<AddmmBackward>)
tensor(0.2570, grad_fn=<MseLossBackward>)


INFO:root:Training 127/286 done
INFO:root:Training 128/286 done
INFO:root:Training 129/286 done
INFO:root:Training 130/286 done


tensor([[0., 1.]])
tensor([[0.5040, 0.4487]], grad_fn=<AddmmBackward>)
tensor(0.2790, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4925, 0.5054]], grad_fn=<AddmmBackward>)
tensor(0.2565, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5064, 0.4529]], grad_fn=<AddmmBackward>)
tensor(0.2779, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4959, 0.5077]], grad_fn=<AddmmBackward>)
tensor(0.2559, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5063, 0.4519]], grad_fn=<AddmmBackward>)
tensor(0.2784, grad_fn=<MseLossBackward>)


INFO:root:Training 131/286 done
INFO:root:Training 132/286 done
INFO:root:Training 133/286 done
INFO:root:Training 134/286 done
INFO:root:Training 135/286 done


tensor([[1., 0.]])
tensor([[0.4960, 0.5068]], grad_fn=<AddmmBackward>)
tensor(0.2554, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5068, 0.4500]], grad_fn=<AddmmBackward>)
tensor(0.2797, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4947, 0.5040]], grad_fn=<AddmmBackward>)
tensor(0.2546, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5016, 0.4493]], grad_fn=<AddmmBackward>)
tensor(0.2775, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4923, 0.5028]], grad_fn=<AddmmBackward>)
tensor(0.2553, grad_fn=<MseLossBackward>)


INFO:root:Training 136/286 done
INFO:root:Training 137/286 done
INFO:root:Training 138/286 done
INFO:root:Training 139/286 done
INFO:root:Training 140/286 done


tensor([[0., 1.]])
tensor([[0.4997, 0.4477]], grad_fn=<AddmmBackward>)
tensor(0.2774, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4933, 0.5047]], grad_fn=<AddmmBackward>)
tensor(0.2558, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5035, 0.4481]], grad_fn=<AddmmBackward>)
tensor(0.2791, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4944, 0.5055]], grad_fn=<AddmmBackward>)
tensor(0.2556, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5050, 0.4509]], grad_fn=<AddmmBackward>)
tensor(0.2783, grad_fn=<MseLossBackward>)


INFO:root:Training 141/286 done
INFO:root:Training 142/286 done
INFO:root:Training 143/286 done
INFO:root:Training 144/286 done
INFO:root:Training 145/286 done


tensor([[1., 0.]])
tensor([[0.4954, 0.5050]], grad_fn=<AddmmBackward>)
tensor(0.2548, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5056, 0.4527]], grad_fn=<AddmmBackward>)
tensor(0.2776, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4926, 0.5008]], grad_fn=<AddmmBackward>)
tensor(0.2541, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5052, 0.4517]], grad_fn=<AddmmBackward>)
tensor(0.2780, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4955, 0.5055]], grad_fn=<AddmmBackward>)
tensor(0.2550, grad_fn=<MseLossBackward>)


INFO:root:Training 146/286 done
INFO:root:Training 147/286 done
INFO:root:Training 148/286 done
INFO:root:Training 149/286 done
INFO:root:Training 150/286 done


tensor([[0., 1.]])
tensor([[0.5065, 0.4546]], grad_fn=<AddmmBackward>)
tensor(0.2770, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4927, 0.5002]], grad_fn=<AddmmBackward>)
tensor(0.2538, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5063, 0.4533]], grad_fn=<AddmmBackward>)
tensor(0.2776, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4936, 0.5029]], grad_fn=<AddmmBackward>)
tensor(0.2547, grad_fn=<MseLossBackward>)


INFO:root:Training 151/286 done
INFO:root:Training 152/286 done
INFO:root:Training 153/286 done
INFO:root:Training 154/286 done


tensor([[0., 1.]])
tensor([[0.5014, 0.4471]], grad_fn=<AddmmBackward>)
tensor(0.2785, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4960, 0.5053]], grad_fn=<AddmmBackward>)
tensor(0.2547, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5070, 0.4540]], grad_fn=<AddmmBackward>)
tensor(0.2776, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4962, 0.5057]], grad_fn=<AddmmBackward>)
tensor(0.2548, grad_fn=<MseLossBackward>)


INFO:root:Training 155/286 done
INFO:root:Training 156/286 done
INFO:root:Training 157/286 done
INFO:root:Training 158/286 done


tensor([[0., 1.]])
tensor([[0.5046, 0.4530]], grad_fn=<AddmmBackward>)
tensor(0.2769, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4951, 0.5047]], grad_fn=<AddmmBackward>)
tensor(0.2548, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5062, 0.4532]], grad_fn=<AddmmBackward>)
tensor(0.2776, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4927, 0.5026]], grad_fn=<AddmmBackward>)
tensor(0.2550, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5043, 0.4540]], grad_fn=<AddmmBackward>)
tensor(0.2762, grad_fn=<MseLossBackward>)


INFO:root:Training 159/286 done
INFO:root:Training 160/286 done
INFO:root:Training 161/286 done
INFO:root:Training 162/286 done
INFO:root:Training 163/286 done
INFO:root:Training 164/286 done


tensor([[1., 0.]])
tensor([[0.4948, 0.5061]], grad_fn=<AddmmBackward>)
tensor(0.2557, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5070, 0.4582]], grad_fn=<AddmmBackward>)
tensor(0.2753, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4933, 0.5002]], grad_fn=<AddmmBackward>)
tensor(0.2535, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5060, 0.4564]], grad_fn=<AddmmBackward>)
tensor(0.2758, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4924, 0.4984]], grad_fn=<AddmmBackward>)
tensor(0.2530, grad_fn=<MseLossBackward>)


INFO:root:Training 165/286 done
INFO:root:Training 166/286 done
INFO:root:Training 167/286 done
INFO:root:Training 168/286 done


tensor([[0., 1.]])
tensor([[0.5048, 0.4538]], grad_fn=<AddmmBackward>)
tensor(0.2766, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4955, 0.5045]], grad_fn=<AddmmBackward>)
tensor(0.2545, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5061, 0.4559]], grad_fn=<AddmmBackward>)
tensor(0.2761, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4952, 0.5058]], grad_fn=<AddmmBackward>)
tensor(0.2553, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5050, 0.4566]], grad_fn=<AddmmBackward>)
tensor(0.2752, grad_fn=<MseLossBackward>)


INFO:root:Training 169/286 done
INFO:root:Training 170/286 done
INFO:root:Training 171/286 done
INFO:root:Training 172/286 done
INFO:root:Training 173/286 done


tensor([[1., 0.]])
tensor([[0.4931, 0.5027]], grad_fn=<AddmmBackward>)
tensor(0.2548, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5028, 0.4547]], grad_fn=<AddmmBackward>)
tensor(0.2751, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4960, 0.5084]], grad_fn=<AddmmBackward>)
tensor(0.2562, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5017, 0.4542]], grad_fn=<AddmmBackward>)
tensor(0.2748, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4961, 0.5061]], grad_fn=<AddmmBackward>)
tensor(0.2550, grad_fn=<MseLossBackward>)


INFO:root:Training 174/286 done
INFO:root:Training 175/286 done
INFO:root:Training 176/286 done
INFO:root:Training 177/286 done
INFO:root:Training 178/286 done


tensor([[0., 1.]])
tensor([[0.5020, 0.4553]], grad_fn=<AddmmBackward>)
tensor(0.2744, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4946, 0.5035]], grad_fn=<AddmmBackward>)
tensor(0.2544, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5019, 0.4528]], grad_fn=<AddmmBackward>)
tensor(0.2757, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4954, 0.5045]], grad_fn=<AddmmBackward>)
tensor(0.2545, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5025, 0.4515]], grad_fn=<AddmmBackward>)
tensor(0.2767, grad_fn=<MseLossBackward>)


INFO:root:Training 179/286 done
INFO:root:Training 180/286 done
INFO:root:Training 181/286 done
INFO:root:Training 182/286 done
INFO:root:Training 183/286 done


tensor([[1., 0.]])
tensor([[0.4975, 0.5046]], grad_fn=<AddmmBackward>)
tensor(0.2536, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5055, 0.4523]], grad_fn=<AddmmBackward>)
tensor(0.2778, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4944, 0.5027]], grad_fn=<AddmmBackward>)
tensor(0.2542, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5025, 0.4531]], grad_fn=<AddmmBackward>)
tensor(0.2758, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4981, 0.5063]], grad_fn=<AddmmBackward>)
tensor(0.2541, grad_fn=<MseLossBackward>)


INFO:root:Training 184/286 done
INFO:root:Training 185/286 done
INFO:root:Training 186/286 done
INFO:root:Training 187/286 done
INFO:root:Training 188/286 done


tensor([[0., 1.]])
tensor([[0.5064, 0.4586]], grad_fn=<AddmmBackward>)
tensor(0.2748, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4958, 0.5045]], grad_fn=<AddmmBackward>)
tensor(0.2543, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5022, 0.4550]], grad_fn=<AddmmBackward>)
tensor(0.2746, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4975, 0.5072]], grad_fn=<AddmmBackward>)
tensor(0.2548, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5047, 0.4576]], grad_fn=<AddmmBackward>)
tensor(0.2745, grad_fn=<MseLossBackward>)


INFO:root:Training 189/286 done
INFO:root:Training 190/286 done
INFO:root:Training 191/286 done
INFO:root:Training 192/286 done
INFO:root:Training 193/286 done


tensor([[1., 0.]])
tensor([[0.4982, 0.5079]], grad_fn=<AddmmBackward>)
tensor(0.2549, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5035, 0.4548]], grad_fn=<AddmmBackward>)
tensor(0.2754, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4971, 0.5061]], grad_fn=<AddmmBackward>)
tensor(0.2545, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5053, 0.4580]], grad_fn=<AddmmBackward>)
tensor(0.2745, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4967, 0.5056]], grad_fn=<AddmmBackward>)

INFO:root:Training 194/286 done
INFO:root:Training 195/286 done
INFO:root:Training 196/286 done
INFO:root:Training 197/286 done



tensor(0.2545, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5067, 0.4614]], grad_fn=<AddmmBackward>)
tensor(0.2734, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4964, 0.5051]], grad_fn=<AddmmBackward>)
tensor(0.2544, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5059, 0.4584]], grad_fn=<AddmmBackward>)
tensor(0.2746, grad_fn=<MseLossBackward>)


INFO:root:Training 198/286 done
INFO:root:Training 199/286 done
INFO:root:Training 200/286 done
INFO:root:Training 201/286 done


tensor([[1., 0.]])
tensor([[0.4943, 0.5011]], grad_fn=<AddmmBackward>)
tensor(0.2534, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5048, 0.4577]], grad_fn=<AddmmBackward>)
tensor(0.2744, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4941, 0.5018]], grad_fn=<AddmmBackward>)
tensor(0.2539, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5066, 0.4611]], grad_fn=<AddmmBackward>)
tensor(0.2735, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4951, 0.5012]], grad_fn=<AddmmBackward>)
tensor(0.2530, grad_fn=<MseLossBackward>)


INFO:root:Training 202/286 done
INFO:root:Training 203/286 done
INFO:root:Training 204/286 done
INFO:root:Training 205/286 done
INFO:root:Training 206/286 done


tensor([[0., 1.]])
tensor([[0.5024, 0.4580]], grad_fn=<AddmmBackward>)
tensor(0.2731, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4940, 0.5024]], grad_fn=<AddmmBackward>)
tensor(0.2542, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5047, 0.4600]], grad_fn=<AddmmBackward>)
tensor(0.2732, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4953, 0.5062]], grad_fn=<AddmmBackward>)
tensor(0.2555, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5006, 0.4564]], grad_fn=<AddmmBackward>)
tensor(0.2730, grad_fn=<MseLossBackward>)


INFO:root:Training 207/286 done
INFO:root:Training 208/286 done
INFO:root:Training 209/286 done
INFO:root:Training 210/286 done
INFO:root:Training 211/286 done


tensor([[1., 0.]])
tensor([[0.4972, 0.5044]], grad_fn=<AddmmBackward>)
tensor(0.2536, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5051, 0.4620]], grad_fn=<AddmmBackward>)
tensor(0.2723, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4929, 0.4991]], grad_fn=<AddmmBackward>)
tensor(0.2531, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5020, 0.4591]], grad_fn=<AddmmBackward>)
tensor(0.2723, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4942, 0.5051]], grad_fn=<AddmmBackward>)
tensor(0.2555, grad_fn=<MseLossBackward>)


INFO:root:Training 212/286 done
INFO:root:Training 213/286 done
INFO:root:Training 214/286 done
INFO:root:Training 215/286 done
INFO:root:Training 216/286 done


tensor([[0., 1.]])
tensor([[0.5024, 0.4595]], grad_fn=<AddmmBackward>)
tensor(0.2723, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4965, 0.5058]], grad_fn=<AddmmBackward>)
tensor(0.2547, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5065, 0.4622]], grad_fn=<AddmmBackward>)
tensor(0.2729, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4920, 0.4953]], grad_fn=<AddmmBackward>)
tensor(0.2517, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5064, 0.4619]], grad_fn=<AddmmBackward>)
tensor(0.2730, grad_fn=<MseLossBackward>)


INFO:root:Training 217/286 done
INFO:root:Training 218/286 done
INFO:root:Training 219/286 done
INFO:root:Training 220/286 done
INFO:root:Training 221/286 done


tensor([[1., 0.]])
tensor([[0.4937, 0.5013]], grad_fn=<AddmmBackward>)
tensor(0.2538, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5009, 0.4559]], grad_fn=<AddmmBackward>)
tensor(0.2735, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4958, 0.5036]], grad_fn=<AddmmBackward>)
tensor(0.2539, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5028, 0.4586]], grad_fn=<AddmmBackward>)
tensor(0.2730, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4978, 0.5062]], grad_fn=<AddmmBackward>)
tensor(0.2542, grad_fn=<MseLossBackward>)


INFO:root:Training 222/286 done
INFO:root:Training 223/286 done
INFO:root:Training 224/286 done
INFO:root:Training 225/286 done
INFO:root:Training 226/286 done


tensor([[0., 1.]])
tensor([[0.5015, 0.4569]], grad_fn=<AddmmBackward>)
tensor(0.2733, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4972, 0.5056]], grad_fn=<AddmmBackward>)
tensor(0.2542, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5002, 0.4551]], grad_fn=<AddmmBackward>)
tensor(0.2736, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4978, 0.5060]], grad_fn=<AddmmBackward>)
tensor(0.2541, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5070, 0.4630]], grad_fn=<AddmmBackward>)
tensor(0.2727, grad_fn=<MseLossBackward>)


INFO:root:Training 227/286 done
INFO:root:Training 228/286 done
INFO:root:Training 229/286 done
INFO:root:Training 230/286 done
INFO:root:Training 231/286 done


tensor([[1., 0.]])
tensor([[0.4922, 0.4948]], grad_fn=<AddmmBackward>)
tensor(0.2513, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5020, 0.4577]], grad_fn=<AddmmBackward>)
tensor(0.2731, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4994, 0.5098]], grad_fn=<AddmmBackward>)
tensor(0.2552, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5053, 0.4626]], grad_fn=<AddmmBackward>)
tensor(0.2721, grad_fn=<MseLossBackward>)


INFO:root:Training 232/286 done
INFO:root:Training 233/286 done
INFO:root:Training 234/286 done
INFO:root:Training 235/286 done


tensor([[1., 0.]])
tensor([[0.4950, 0.5005]], grad_fn=<AddmmBackward>)
tensor(0.2528, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5043, 0.4627]], grad_fn=<AddmmBackward>)
tensor(0.2715, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4969, 0.5037]], grad_fn=<AddmmBackward>)
tensor(0.2534, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5036, 0.4604]], grad_fn=<AddmmBackward>)
tensor(0.2724, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4933, 0.4984]], grad_fn=<AddmmBackward>)
tensor(0.2526, grad_fn=<MseLossBackward>)


INFO:root:Training 236/286 done
INFO:root:Training 237/286 done
INFO:root:Training 238/286 done
INFO:root:Training 239/286 done
INFO:root:Training 240/286 done


tensor([[0., 1.]])
tensor([[0.5047, 0.4620]], grad_fn=<AddmmBackward>)
tensor(0.2721, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4933, 0.4948]], grad_fn=<AddmmBackward>)
tensor(0.2508, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5044, 0.4606]], grad_fn=<AddmmBackward>)
tensor(0.2727, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4915, 0.4957]], grad_fn=<AddmmBackward>)
tensor(0.2522, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5008, 0.4577]], grad_fn=<AddmmBackward>)
tensor(0.2724, grad_fn=<MseLossBackward>)


INFO:root:Training 241/286 done
INFO:root:Training 242/286 done
INFO:root:Training 243/286 done
INFO:root:Training 244/286 done
INFO:root:Training 245/286 done


tensor([[1., 0.]])
tensor([[0.4969, 0.5064]], grad_fn=<AddmmBackward>)
tensor(0.2548, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5057, 0.4660]], grad_fn=<AddmmBackward>)
tensor(0.2705, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.5001, 0.5117]], grad_fn=<AddmmBackward>)
tensor(0.2559, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5029, 0.4616]], grad_fn=<AddmmBackward>)
tensor(0.2714, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4979, 0.5054]], grad_fn=<AddmmBackward>)
tensor(0.2538, grad_fn=<MseLossBackward>)


INFO:root:Training 246/286 done
INFO:root:Training 247/286 done
INFO:root:Training 248/286 done
INFO:root:Training 249/286 done
INFO:root:Training 250/286 done


tensor([[0., 1.]])
tensor([[0.5038, 0.4620]], grad_fn=<AddmmBackward>)
tensor(0.2716, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4893, 0.4898]], grad_fn=<AddmmBackward>)
tensor(0.2504, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5081, 0.4691]], grad_fn=<AddmmBackward>)
tensor(0.2700, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4922, 0.4963]], grad_fn=<AddmmBackward>)
tensor(0.2521, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5068, 0.4692]], grad_fn=<AddmmBackward>)
tensor(0.2693, grad_fn=<MseLossBackward>)


INFO:root:Training 251/286 done
INFO:root:Training 252/286 done
INFO:root:Training 253/286 done
INFO:root:Training 254/286 done
INFO:root:Training 255/286 done


tensor([[1., 0.]])
tensor([[0.4947, 0.5027]], grad_fn=<AddmmBackward>)
tensor(0.2540, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5038, 0.4678]], grad_fn=<AddmmBackward>)
tensor(0.2685, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4888, 0.4926]], grad_fn=<AddmmBackward>)
tensor(0.2520, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5065, 0.4723]], grad_fn=<AddmmBackward>)
tensor(0.2675, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4864, 0.4883]], grad_fn=<AddmmBackward>)
tensor(0.2511, grad_fn=<MseLossBackward>)


INFO:root:Training 256/286 done
INFO:root:Training 257/286 done
INFO:root:Training 258/286 done
INFO:root:Training 259/286 done
INFO:root:Training 260/286 done


tensor([[0., 1.]])
tensor([[0.5080, 0.4746]], grad_fn=<AddmmBackward>)
tensor(0.2671, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4922, 0.5021]], grad_fn=<AddmmBackward>)
tensor(0.2550, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5028, 0.4685]], grad_fn=<AddmmBackward>)
tensor(0.2676, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4934, 0.5079]], grad_fn=<AddmmBackward>)
tensor(0.2573, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5018, 0.4675]], grad_fn=<AddmmBackward>)
tensor(0.2677, grad_fn=<MseLossBackward>)


INFO:root:Training 261/286 done
INFO:root:Training 262/286 done
INFO:root:Training 263/286 done
INFO:root:Training 264/286 done
INFO:root:Training 265/286 done


tensor([[1., 0.]])
tensor([[0.4940, 0.5059]], grad_fn=<AddmmBackward>)
tensor(0.2559, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.4994, 0.4624]], grad_fn=<AddmmBackward>)
tensor(0.2692, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4933, 0.5026]], grad_fn=<AddmmBackward>)
tensor(0.2547, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5030, 0.4670]], grad_fn=<AddmmBackward>)
tensor(0.2686, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4902, 0.4975]], grad_fn=<AddmmBackward>)
tensor(0.2537, grad_fn=<MseLossBackward>)


INFO:root:Training 266/286 done
INFO:root:Training 267/286 done
INFO:root:Training 268/286 done
INFO:root:Training 269/286 done
INFO:root:Training 270/286 done


tensor([[0., 1.]])
tensor([[0.5019, 0.4671]], grad_fn=<AddmmBackward>)
tensor(0.2680, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4933, 0.5015]], grad_fn=<AddmmBackward>)
tensor(0.2541, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.4996, 0.4620]], grad_fn=<AddmmBackward>)
tensor(0.2695, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4933, 0.5025]], grad_fn=<AddmmBackward>)
tensor(0.2546, grad_fn=<MseLossBackward>)


INFO:root:Training 271/286 done
INFO:root:Training 272/286 done
INFO:root:Training 273/286 done
INFO:root:Training 274/286 done


tensor([[0., 1.]])
tensor([[0.5038, 0.4641]], grad_fn=<AddmmBackward>)
tensor(0.2705, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4956, 0.5043]], grad_fn=<AddmmBackward>)
tensor(0.2543, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.4988, 0.4575]], grad_fn=<AddmmBackward>)
tensor(0.2716, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4964, 0.5081]], grad_fn=<AddmmBackward>)
tensor(0.2559, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5001, 0.4616]], grad_fn=<AddmmBackward>)
tensor(0.2700, grad_fn=<MseLossBackward>)


INFO:root:Training 275/286 done
INFO:root:Training 276/286 done
INFO:root:Training 277/286 done
INFO:root:Training 278/286 done
INFO:root:Training 279/286 done


tensor([[1., 0.]])
tensor([[0.4982, 0.5095]], grad_fn=<AddmmBackward>)
tensor(0.2557, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.4996, 0.4601]], grad_fn=<AddmmBackward>)
tensor(0.2706, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4945, 0.4994]], grad_fn=<AddmmBackward>)
tensor(0.2524, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5016, 0.4602]], grad_fn=<AddmmBackward>)
tensor(0.2715, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4960, 0.5028]], grad_fn=<AddmmBackward>)
tensor(0.2534, grad_fn=<MseLossBackward>)


INFO:root:Training 280/286 done
INFO:root:Training 281/286 done
INFO:root:Training 282/286 done
INFO:root:Training 283/286 done
INFO:root:Training 284/286 done


tensor([[0., 1.]])
tensor([[0.5038, 0.4665]], grad_fn=<AddmmBackward>)
tensor(0.2692, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4964, 0.5045]], grad_fn=<AddmmBackward>)
tensor(0.2540, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5082, 0.4706]], grad_fn=<AddmmBackward>)
tensor(0.2692, grad_fn=<MseLossBackward>)
tensor([[1., 0.]])
tensor([[0.4920, 0.4973]], grad_fn=<AddmmBackward>)
tensor(0.2527, grad_fn=<MseLossBackward>)
tensor([[0., 1.]])
tensor([[0.5064, 0.4735]], grad_fn=<AddmmBackward>)
tensor(0.2668, grad_fn=<MseLossBackward>)


INFO:root:Training 285/286 done
